
<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">                      
				  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" id="txtFindBoards" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" width="32px" height="32px" style="border-radius:50%" /></a>
					</li>
				</ul>
				<!-- translation-button -->
				<ul id="translation-dropdown" class="dropdown-content">
				  <li>
					<a href="userProfile?userId=<?php echo $userId ?>"><img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" width="32px" height="32px" alt="Profile" />  <span class="language-select">Profile</span></a>
				  </li>
				  <li>
					<a href="javascript:void(0);" onclick="cekLogout()"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
				  </li>
				  
				</ul>
			</div>
		</nav>

		<!-- HORIZONTL NAV START-->
		 <nav id="horizontal-nav" class="white hide-on-med-and-down">
			<div class="nav-wrapper">                  
			  <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
				<li>
					<a href="home" class="cyan-text">
						<i class="mdi-action-dashboard"></i>
						<span>Home</span>
					</a>
				</li>
				<?php
					if($role == "Creator")
					{
						echo '<li class="roleCreator" style="">';
					}
					else
					{
						echo '<li class="roleCreator" style="display:none;">';
					}
				?>
					<a href="javascript:void(0);" onclick="openModalInvite()" class="cyan-text">
						<i class="mdi-social-person-add"></i>
						<span>Invite</span>
					</a>
				</li>
				<li>
					<a href="javascript:void(0);" onclick="openStatus()" class="cyan-text">
						<i class="mdi-action-assignment"></i>
						<span>Status</span>
					</a>
				</li>
				<li>
					<?php
						if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listCreate == "1") || ($role == "Client" && $roleClient->listCreate == "1") )
						{
							echo '<a href="#modalcreatelist" class="cyan-text modal-trigger roleCreateList">';
						}
						else
						{
							echo '<a href="#modalcreatelist" class="cyan-text modal-trigger roleCreateList" style="display:none;">';
						}
					?>
					
						<i class="mdi-action-list"></i>
						<span>Create List</span>
					</a>
				</li> 
				<li>
					<?php
						if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listCreate == "1") || ($role == "Client" && $roleClient->listCreate == "1") )
						{
							echo '<a href="#modalcreatecarddua" class="cyan-text modal-trigger roleCreateCard">';
						}
						else
						{
							echo '<a href="#modalcreatecarddua" class="cyan-text modal-trigger roleCreateCard" style="display:none;">';
						}
					?>
					
						<i class="mdi-content-add"></i>
						<span>Create Card</span>
					</a>
				</li>
				<li>
					<a href="javascript:void(0);" class="cyan-text chat-collapse " data-activates="chat-out" data-sidenav="right" data-closeonclick="false">
						<i class="mdi-communication-chat"></i>
						<span>Chat Board</span>
					</a>
				</li>
				<li>
					<a href="<?php 
					$boardId = "";
					foreach($board as $r)
					{
						$boardId = $r->boardId;
					}
					echo "calendar?id=".$boardId; 

					?>" class="cyan-text">
						<i class="mdi-action-schedule"></i>
						<span>Calender Board</span>
					</a>
				</li>
				<li>
					<a href="javascript:void(0);" onclick="ajaxModalMore()" class="cyan-text">
						<i class="mdi-navigation-more-horiz"></i>
						<span>More</span>
					</a>
				</li>
			  </ul>
			</div>
		  </nav>
		<!-- HORIZONTL NAV END-->
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav hide-on-large-only">
    <ul id="slide-out" class="side-nav leftside-navigation ">
        <li class="user-details cyan darken-2">
            <div class="row">
                <div class="col col s4 m4 l4">
                    <img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" alt="" class="circle responsive-img valign profile-image">
                </div>
                <div class="col col s8 m8 l8">
                    <a class="dropdown-button waves-effect waves-light profile-btn white-text" href="javascript:void(0);" disabled><?php echo $userProfile->userName ?><i class="mdi-navigation-arrow-drop-down right"></i></a>
                </div>
            </div>
        </li>
        <li class="bold active"><a href="home" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Home</a>
        </li>
        <li class="bold active roleClient"><a href="javascript:void(0);" onclick="openModalInvite()" class="waves-effect waves-cyan"><i class="mdi-social-person-add"></i>Invite</a>
        </li>
        <li class="bold active"><a href="#modalcreatelist" class="waves-effect waves-cyan modal-trigger"><i class="mdi-action-list"></i> Create List</a>
        </li>
        <li class="bold active"><a href="#modalcreatecard" class="waves-effect waves-cyan modal-trigger"><i class="mdi-content-add"></i> Create Card</a>
        </li>
        <li class="bold active"><a href="javascript:void(0);" class="cyan-text chat-collapse " data-activates="chat-out" data-sidenav="right" data-closeonclick="false"><i class="mdi-communication-chat"></i>Chat Board</a>
        </li>
        <li class="bold active"><a href="calender" class="waves-effect waves-cyan"><i class="mdi-action-schedule"></i> Calender Board</a>
        </li>
        <li class="bold active"><a href="#modalmore" class="waves-effect waves-cyan modal-trigger"><i class="mdi-navigation-more-horiz"></i> More</a>
        </li>
        <div class="divider"></div>
        <li class="bold active"><a href="javascript:void(0);" class="waves-effect waves-cyan">Profile</a>
        </li>
        <li class="bold active"><a href="javascript:void(0);" class="waves-effect waves-cyan">Log Out</a>
        </li>
    </ul>
    <a href="javascript:void(0);" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>

<!-- START MAIN -->
<div id="main">
	<div id="result"></div>
	<!-- START WRAPPER -->
	<div class="wrapper">

		<!-- START CONTENT -->
		<section id="content">

			<!--start container-->
			<div class="container">
				<!-- trello start here -->
				<div class="section">
					<!-- BOARD -->
					<div class="row" style="margin-top:-20px;">
						<div class="col s6 m4 l4">
							<h1><b>
								<?php
									foreach($board as $r)
									{
										echo "<p id='boardTitle'>".$r->boardTitle."</p>";
										echo "<input type='hidden' id='hiddenBoardId' value='".$r->boardId."'>";
										echo "<input type='hidden' id='hiddenUserId' value='".$userId."'>";
										echo "<input type='hidden' id='hiddenUserRole' value='".$role."'>";

									}
								?>
							</b></h1>
						</div>
						<div class="col s6 m4 l8">
							<p><b><u>Filter Card</u></b></p>
							<input type="checkbox" id="filterred" onchange="setFilter()" />
	                      	<label for="filterred"><div style="background-color:red;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filteryellow" onchange="setFilter()"/>
	                      	<label for="filteryellow"><div style="background-color:yellow;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filtergreen" onchange="setFilter()" />
	                      	<label for="filtergreen"><div style="background-color:green;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filterblue" onchange="setFilter()"/>
	                      	<label for="filterblue"><div style="background-color:blue;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
						</div>
					</div>
					</div>
					<!-- MODAL MENU BOARD-->
					<div id="modalinvite" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<div class="col s12 m6 l6">
									<p><b>Invite</b></p>
									<input type="email" placeholder="Email" id="inviteEmail">
									<label>Invite as..</label>
									<select id="inviteRoleMember">
										<option value="Collaborator">Collaborator</option>
										<option value="Client">Client</option>
									</select>
									<a href="javacsript:void(0);" class="waves-effect waves-red btn" onclick="sendInvite()">Invite</a>

								</div>
								<div class="col s12 m6 l12">
									<p><b>Members</b></p>
									<div class="row" id="ajaxInviteMember">
									</div>
								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javacsript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					  </div>
					</div>
					<div id="modalcreatelist" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Create a list..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" placeholder="Title.." id="listTitle">
								<input type="hidden" id="hiddenListId">
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a class="waves-effect waves-red btn-flat modal-action modal-close" onclick="createList()">Save</a>
					  </div>
					</div>
					<div id="modalstatus" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Board status..</b></h6>
								<p>Board deadline..</p>
									<input type="date" class="datepicker" id="progressDate">
								<p>Progress</p>
									<div id="ajaxProgressChecklist">
									</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a class="waves-effect waves-red btn-flat modal-action modal-close" onclick="createStatus()">Save</a>
					  </div>
					</div>
					<div id="modalcreatecard" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Create a card..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" placeholder="Title.." id="titleCard">
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a class="waves-effect waves-red btn-flat modal-action modal-close" onclick="createCard()">Save</a>
					  </div>
					</div>
					<div id="modalcreatecarddua" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Create a card..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" placeholder="Title.." id="titleCardManual">
								<select id="listCardManual">
									<option value="0"  disabled selected>Choose list..</option>
									<?php
										foreach($boardList as $l)
										{
											echo '<option class="black-text" value="'.$l->listId.'">'.$l->listTitle.'</option>';
										}
									?>

								</select>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a onclick="createCardDua()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalmore" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>More Menu..</b></h6>    
								<div class="col s12 m6 l6">
									<?php
										if($role == "Creator")
										{
											echo '<div class="col s12 m6 l12 roleCreator" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleCreator" style="display:none;">';
										}
									?>
									
										<a class="btn-flat dropdown-button waves-effect black-text" href="javascript:void(0);" data-activates="dropdownboard">Change Background<i class="mdi-navigation-arrow-drop-down right"></i></a>
											<ul id="dropdownboard" class="dropdown-content">
												<li onclick="changeBackground('red')">
													<div class="col s12 m6 l9">
														<div style="background-color:red;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
													</div>
													<div class="col s12 m6 l2">
														<i id="bgRed" style="margin:5px;display:none;" class="mdi-navigation-check black-text"></i>
													</div>
												</li>
												<li onclick="changeBackground('yellow')">
													<div class="col s12 m6 l9">
														<div style="background-color:yellow;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
													</div>
													<div class="col s12 m6 l2">
														<i id="bgYellow" style="margin:5px;display:none;" class="mdi-navigation-check black-text"></i>
													</div>
												</li>
												<li onclick="changeBackground('green')">
													<div class="col s12 m6 l9">
														<div style="background-color:green;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
													</div>
													<div class="col s12 m6 l2">
														<i id="bgGreen" style="margin:5px;display:none;" class="mdi-navigation-check black-text"></i>
													</div>
												</li>
												<li onclick="changeBackground('blue')">
													<div class="col s12 m6 l9">
														<div style="background-color:blue;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
													</div>
													<div class="col s12 m6 l2">
														<i id="bgBlue" style="margin:5px;display:none;" class="mdi-navigation-check black-text"></i>
													</div>
												</li>
											</ul>
									</div>
									<div class="col s12 m6 l12">
										<p>
										<input type="checkbox" id="testfav" onchange="createFavorite()"/>
										<label for="testfav" class="black-text">Favorite</label>
										</p>
									</div>
									<div class="col s12 m6 l12">
										<p>
										<input type="checkbox" id="testsub" onchange="createSubscribe()" />
										<label for="testsub" class="black-text">Subscribe</label>
										</p>
									</div>
									<?php
										if($role=="Creator")
										{
											echo '<div class="col s12 m6 l12 roleCreator" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleCreator" style="display:none;">';
										}
									?>
									
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openRole()">Setting Role</a>
									</div>
									<?php
										if($role == "Collaborator" || $role == "Client")
										{
											echo '<div class="col s12 m6 l12 roleCollaboratorClient" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleCollaboratorClient" style="display:none;">';
										}
									?>
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="leaveBoard()">Leave Board</a>
									</div>

								</div>
								<div class="col s12 m6 l6">
									<div class="col s12 m6 l12">
										<?php
											if($role == "Creator")
											{
												echo '<a class="btn-flat waves-effect black-text modal-trigger roleCreator" style="" href="#modaleditboard">Edit Board</a>';
											}
											else
											{
												echo '<a class="btn-flat waves-effect black-text modal-trigger roleCreator" style="display:none;" href="#modaleditboard">Edit Board</a>';
											}
										?>
										
									</div>
									<div class="col s12 m6 l12">
										<a class="btn-flat waves-effect black-text modal-trigger" href="#modalcopyboard">Copy Board</a>
									</div>
									<div class="col s12 m6 l12">
										<a class="btn-flat dropdown-button waves-effect black-text" href="javascript:void(0);" data-activates="dropdownexport">Export<i class="mdi-navigation-arrow-drop-down right"></i></a>
										
										<ul id="dropdownexport" class="dropdown-content">
											<li>
												<a href="javascript:void(0);" onclick="createPDF()">PDF</a>
											</li>
											<li>
												<a href="javascript:void(0);" onclick="createExcel()">Excel</a>
											</li>
										</ul>
									</div>
									<div class="divider"></div>
									<div class="col s12 m6 l12">
										<a class="btn-flat waves-effect black-text modal-trigger" href="#modalarchive" onclick="modalArchive()">Archive</a>
									</div>
									<div class="col s12 m6 l12">
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openModalGanttChart()">Gantt Chart</a>
									</div>
									<?php
										if($role == "Creator")
										{
											echo '<div class="col s12 m6 l12 roleCreator" style="" id="closeboard">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleCreator" style="display:none;" id="closeboard">';
										}
									?>
									
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="closeBoard()">Close Board</a>
									</div>
									<div class="col s12 m6 l12" id="openboard" style="display:none;">
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openBoard()">Open Board</a>
									</div>

								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					  </div>
					</div>


					<!-- END OF MODAL MENU BOARD-->
					<!-- MODAL LIST-->
					<div id="modallistmenu" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>List Menu..</b></h6>    
								<div class="col s12 m6 l12">
									<div class="col s12 m6 l12">
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardCreate == "1") || ($role == "Client" && $roleClient->cardCreate == "1") )
										{
											echo '<a class="btn-flat waves-effect black-text roleCreateCardMenu" href="javascript:void(0);" onclick="openModalListAddCard()" style="">Add a card..</a>';
										}
										else
										{
											echo '<a class="btn-flat waves-effect black-text roleCreateCardMenu" href="javascript:void(0);" onclick="openModalListAddCard()" style="display:none;">Add a card..</a>';
										}
									?>
										
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listCreate == "1") || ($role == "Client" && $roleClient->listCreate == "1") )
										{
											echo '<div class="col s12 m6 l12 roleCreateListMenu" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleCreateListMenu" style="display:none;">';
										}
									?>
									
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openModalListCopyList()">Copy list..</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listEdit == "1") || ($role == "Client" && $roleClient->listEdit == "1") )
										{
											echo '<div class="col s12 m6 l12 roleEditListMenu" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleEditListMenu" style="display:none;">';
										}
									?>
									
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openModalMoveList()">Move list..</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardEdit == "1") || ($role == "Client" && $roleClient->cardEdit == "1") )
										{
											echo '<div class="col s12 m6 l12 roleEditCardMenu" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleEditCardMenu" style="display:none;">';
										}
									?>
									
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openModalListMoveAllCard()">Move all card in this list..</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardDelete == "1") || ($role == "Client" && $roleClient->cardDelete == "1") )
										{
											echo '<div class="col s12 m6 l12 roleDeleteCardMenu" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleDeleteCardMenu" style="display:none;">';
										}
									?>
									
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openModalListArchiveAllCard()">Archive all card in this list..</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listDelete == "1") || ($role == "Client" && $roleClient->listDelete == "1") )
										{
											echo '<div class="col s12 m6 l12 roleDeleteListMenu" style="">';
										}
										else
										{
											echo '<div class="col s12 m6 l12 roleDeleteListMenu" style="display:none;">';
										}
									?>
									
										<a class="btn-flat waves-effect black-text" href="javascript:void(0);" onclick="openModalListArchiveList()">Archive this list..</a>
									</div>

								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					  </div>
					</div>
					<div id="modalcopylist" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Copy list..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" placeholder="Title.." id="copyListTitle">
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="createCopyList()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalmovelist" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Move list..</b></h6>
								<div class="divider"></div>
								<p>Position</p>
								<select id="selectListPosition" class="browser-default">
								</select>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="changeListPosition()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalmovecardlist" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Move all card in this list..</b></h6>
								<p>List</p>
								<select id="selectAllCardList" class="browser-default">
								</select>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="saveMoveAllCardList()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<!-- END OF MODAL LIST-->
					<!-- MODAL MENU MORE-->
					<div id="modaleditboard" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Edit board..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" value="" id="txtEditBoard">
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="changeEditBoard()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalganttchart" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<div id="chart_div" class="col s6 m6 l12"></div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					  </div>
					</div>
					<div id="modalcopyboard" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Copy board..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" value="" id="newTitle">
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="copyBoard()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalsettingrole" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Setting role for collaborator and client..</b></h6>
								<div class="divider"></div>
								<div class="col s6 m6 l6">
									<p class="center-align">Role collaborator..</p>
									<p><b><u>List</u></b></p>
									<div class="divider" style="margin-top:-2%;margin-bottom:2%;"></div>
									<div class="">
											<input type="checkbox" id="collListCreate"/>
											<label for="collListCreate" class="black-text">Create</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collListEdit"/>
											<label for="collListEdit" class="black-text">Edit</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collListDelete"/>
											<label for="collListDelete" class="black-text">Archive & delete</label>
					                </div>
					                <br>
					                <p><b><u>Card</u></b></p>
									<div class="divider" style="margin-top:-2%;margin-bottom:2%;"></div>
									<div class="">
											<input type="checkbox" id="collCardCreate"/>
											<label for="collCardCreate" class="black-text">Create</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collCardEdit"/>
											<label for="collCardEdit" class="black-text">Edit</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collCardDelete"/>
											<label for="collCardDelete" class="black-text">Archive & delete</label>
					                </div>
					                <br>
					                <p><b><u>Activity</u></b></p>
									<div class="divider" style="margin-top:-2%;margin-bottom:2%;"></div>
									<div class="">
											<input type="checkbox" id="collActAM"/>
											<label for="collActAM" class="black-text">Assign members</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collActLabel"/>
											<label for="collActLabel" class="black-text">Label card</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collActCheck"/>
											<label for="collActCheck" class="black-text">Checklist</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collActStart"/>
											<label for="collActStart" class="black-text">Start date</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collActDue"/>
											<label for="collActDue" class="black-text">Due date</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="collActAtt"/>
											<label for="collActAtt" class="black-text">Attachment</label>
					                </div>
								</div>
								<div class="col s6 m6 l6">
									<p class="center-align">Role client..</p>
									<p><b><u>List</u></b></p>
									<div class="divider" style="margin-top:-2%;margin-bottom:2%;"></div>
									<div class="">
											<input type="checkbox" id="cliListCreate"/>
											<label for="cliListCreate" class="black-text">Create</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliListEdit"/>
											<label for="cliListEdit" class="black-text">Edit</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliListDelete"/>
											<label for="cliListDelete" class="black-text">Archive & delete</label>
					                </div>
					                <br>
					                <p><b><u>Card</u></b></p>
									<div class="divider" style="margin-top:-2%;margin-bottom:2%;"></div>
									<div class="">
											<input type="checkbox" id="cliCardCreate"/>
											<label for="cliCardCreate" class="black-text">Create</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliCardEdit"/>
											<label for="cliCardEdit" class="black-text">Edit</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliCardDelete"/>
											<label for="cliCardDelete" class="black-text">Archive & delete</label>
					                </div>
					                <br>
					                <p><b><u>Activity</u></b></p>
									<div class="divider" style="margin-top:-2%;margin-bottom:2%;"></div>
									<div class="">
											<input type="checkbox" id="cliActAM"/>
											<label for="cliActAM" class="black-text">Assign members</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliActLabel"/>
											<label for="cliActLabel" class="black-text">Label card</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliActCheck"/>
											<label for="cliActCheck" class="black-text">Checklist</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliActStart"/>
											<label for="cliActStart" class="black-text">Start date</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliActDue"/>
											<label for="cliActDue" class="black-text">Due date</label>
					                </div>
					                <br>
					                <div class="">
											<input type="checkbox" id="cliActAtt"/>
											<label for="cliActAtt" class="black-text">Attachment</label>
					                </div>
								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="createRole()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<!-- END OF MODAL MENU MORE-->
					<!-- MODAL ACTION CARD-->
					<input type="hidden" id="hiddenCardId">
					<div id="modaleditcard" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Edit card title..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" id="txtCardTitle">
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close" onclick="updateCardTitle()">Save</a>
					  </div>
					</div>
					<div id="modaleditdescription" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Edit description card..</b></h6>
								<div class="divider"></div>
								<p>Description</p>
								<textarea id="textareaDescription" class="materialize-textarea"></textarea>
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="updateCardDescription()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalcreatechecklistitem" class="modal">
					  <div class="modal-content">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Add checklist item..</b></h6>
								<div class="divider"></div>
								<p>Item</p>
								<input type="hidden" id="checklistItemId">
								<input type="text" id="checklistItemTitle">
							</div>
						</div>
					  </div>
					  <div class="modal-footer">
						<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="#" onclick="createChecklistItem()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalassignmembers" class="modal modal-fixed-footer white">
					  <div class="modal-content white">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Assign members</b></h6>
								<div class="divider"></div>
								<div id="assignMembers">
								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a onclick="createAssignMembers()" href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modallabelcard" class="modal modal-fixed-footer white">
					  <div class="modal-content white">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Label a card..</b></h6>
								<div class="divider"></div>
									<p>Choose your color..</p>
									<input type="checkbox" style="margin-top:10px;" id="labelred" />
									<label for="labelred"><div style="background-color:red;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
									
									<input type="checkbox" style="margin-top:5px;" id="labelyellow" />
									<label for="labelyellow" ><div style="background-color:yellow;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
									<input type="checkbox" style="margin-top:5px;" id="labelgreen" />
									<label for="labelgreen"><div style="background-color:green;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
									<input type="checkbox" style="margin-top:5px;" id="labelblue" />
									<label for="labelblue"><div style="background-color:blue;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
		
							</div>
						</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="#" onclick="createLabelCard()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalchecklist" class="modal modal-fixed-footer white">
					  <div class="modal-content white">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Add a checklist..</b></h6>
								<div class="divider"></div>
								<p>Title</p>
								<input type="text" id="checklistTitle">
							</div>
						</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a onclick="createChecklist()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalarchive" class="modal modal-fixed-footer white">
					  <div class="modal-content white">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Archived items..</b></h6>
								<div class="divider"></div>
								<div class="col s12 m6 l6" id="archiveList">
									<p><b>Lists</b></p>
									<div class="divider"></div>
								</div>
								<div class="col s12 m6 l6" id="archiveCard">
									<p><b>Cards</b></p>
									<div class="divider"></div>
								</div>
							</div>
						</div>

					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalstartdate" class="modal modal-fixed-footer white">
					  <div class="modal-content white">
						<div class="col s12 m6 l12" >
							<div class="section">
								<h6><b>Add a start date</b></h6>
								<div class="divider"></div>
								<div class="col s12 m6 l3">
									<p>Date</p>
									<input type="date" class="datepicker" id="startDate">
									<p>Time</p>
									<select id="startDateTime">
									  <option value="" disabled selected>Choose your time</option>
									  <option value="0">00:00</option>
									  <option value="1">01:00</option>
									  <option value="2">02:00</option>
									  <option value="3">03:00</option>
									  <option value="4">04:00</option>
									  <option value="5">05:00</option>
									  <option value="6">06:00</option>
									  <option value="7">07:00</option>
									  <option value="8">08:00</option>
									  <option value="9">09:00</option>
									  <option value="10">10:00</option>
									  <option value="11">11:00</option>
									  <option value="12" selected>12:00</option>
									  <option value="13">13:00</option>
									  <option value="14">14:00</option>
									  <option value="15">15:00</option>
									  <option value="16">16:00</option>
									  <option value="17">17:00</option>
									  <option value="18">18:00</option>
									  <option value="19">19:00</option>
									  <option value="20">20:00</option>
									  <option value="21">21:00</option>
									  <option value="22">22:00</option>
									  <option value="23">23:00</option>
									</select>
								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a onclick="modalStartDate()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalduedate" class="modal modal-fixed-footer white" style="height:80%">
					  <div class="modal-content white">
						<div class="col s12 m6 l12" >
							<div class="section">
								<h6><b>Add a due date</b></h6>
								<div class="divider"></div>
								<div class="col s12 m6 l3">
									<p>Date</p>
									<input type="date" class="datepicker" id="dueDate">
									<p>Time</p>
									<select id="dueDateTime">
									  <option value="" disabled selected>Choose your time</option>
									  <option value="0">00:00</option>
									  <option value="1">01:00</option>
									  <option value="2">02:00</option>
									  <option value="3">03:00</option>
									  <option value="4">04:00</option>
									  <option value="5">05:00</option>
									  <option value="6">06:00</option>
									  <option value="7">07:00</option>
									  <option value="8">08:00</option>
									  <option value="9">09:00</option>
									  <option value="10">10:00</option>
									  <option value="11">11:00</option>
									  <option value="12" selected>12:00</option>
									  <option value="13">13:00</option>
									  <option value="14">14:00</option>
									  <option value="15">15:00</option>
									  <option value="16">16:00</option>
									  <option value="17">17:00</option>
									  <option value="18">18:00</option>
									  <option value="19">19:00</option>
									  <option value="20">20:00</option>
									  <option value="21">21:00</option>
									  <option value="22">22:00</option>
									  <option value="23">23:00</option>
									</select>
								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a onclick="modalDueDate()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalattachment" class="modal modal-fixed-footer white">
					</div>
					<div id="modalmove" class="modal modal-fixed-footer white">
					  <div class="modal-content white">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Move card..</b></h6>
								<div class="divider"></div>
								<div class="col s12 m6 l6">
									<p>List</p>
									<select id="selectListCard" class="browser-default" onchange="changeList()">
									</select>
								</div>
								<div class="col s12 m6 l6">
									<p>Position</p>
									<select id="selectCardPosition" class="browser-default">
									</select>
								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="javascript:void(0);" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0);" onclick="changeCardPosition()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<div id="modalcopy" class="modal modal-fixed-footer white">
					  <div class="modal-content white">
						<div class="col s12 m6 l12">
							<div class="row">
								<h6><b>Copy card..</b></h6>
								<div class="divider"></div>
								<div class="col s12 m6 l12">
									<input type="text" placeholder="Title" value="" id="copyCardTitle">
								</div>
								<div class="col s12 m6 l12">
									<p>List</p>
									<select id="copyCardList" class="browser-default">
									</select>
								</div>
							</div>
						</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a href="javascript:void(0)" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
						<a href="javascript:void(0)" onclick="setCopyCard()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					  </div>
					</div>
					<!-- END OF MODAL ACTION CARD-->
					<!-- MODAL CARD-->
					<div id="modal3" class="modal modal-fixed-footer grey lighten-3" style="width:70%;">
					  <div class="modal-content grey lighten-3 black-text left-align">
							<div class="row">
								<div class="col s12 m6 l9">
									<div class="row">
										<div class="col s12 m6 l12">
										<h5 id="modalCardTitle"><b>Card Title</b> </h5>
										<?php
											if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardEdit == "1") || ($role == "Client" && $roleClient->cardEdit == "1") )
											{
												echo '<a href="#modaleditcard" class="ultra-small modal-trigger roleEditCard" style="">Edit Title</a>';
											}
											else
											{
												echo '<a href="#modaleditcard" class="ultra-small modal-trigger roleEditCard" style="display:none;">Edit Title</a>';
											}
										?>

										
										</div>
									</div>
									<div class="row">
										<div class="col s12 m6 l12">
											<h6 class="grey-text lighten-3" id="modalListTitle">in list List Title</h6>
										</div>
									</div>
									<div class="divider"></div>
									<div class="row">
										<div class="col s12 m6 l12" id="cobacoba">
											<h6><b>Description</b></h6>
											<h6 id="modalCardDescription">Ini adalah deskripsi</h6>
											<div id="tes"></div>
											<?php
												if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardEdit == "1") || ($role == "Client" && $roleClient->cardEdit == "1") )
												{
													echo '<a href="#modaleditdescription" class="modal-trigger roleEditCard" style="">Edit description</a>';
												}
												else
												{
													echo '<a href="#modaleditdescription" class="modal-trigger roleEditCard" style="display:none;">Edit description</a>';
												}
											?>
											
										</div>
									</div>
									<div class="divider"></div>
									<div class="row">
										<div class="col 12 m3 l4" id="iconMember">
											<h6><b>Members</b></h6>	
										</div>
										<div class="col 12 m3 l2">
											<div id="ajaxLabelCard">
												<!--<div class="red" style="width:32px;height:32px;border-radius:15%;margin:1px;"></div>
												<div class="yellow" style="width:32px;height:32px;border-radius:15%;margin:1px;"></div>
												<div class="green" style="width:32px;height:32px;border-radius:15%;margin:1px;"></div>
												<div class="blue" style="width:32px;height:32px;border-radius:15%;margin:1px;"></div>-->
											</div>
										</div>
										<div class="col s12 m3 l3">
											<!--<h6><b>Start Date</b></h6>-->
											<div id="ajaxStartDate">
											</div>
										</div>
										<div class="col s12 m3 l3">
											<div id="ajaxDueDate">
											</div>
										</div>
									</div>
									<div class="divider"></div>
									<div class="row" >
										<div class="col s12 m6 l12" id="ajaxAttachment">
										</div>
									</div>
									<div class="divider"></div>
									<div class="row" id="ajaxChecklist">
									</div>
									<div class="divider"></div>
									<div class="row">
										<div class="col s12 m6 l12">
										<h6><b>Add Comment</b></h6>
										<textarea id="textareaComment" class="materialize-textarea" ></textarea> <a class="waves-effect waves-light light-blue lighten-1 btn" onclick="createCardComment()">Save</a>
										</div>
									</div>
									<div class="divider" style="margin-top:5px;"></div>
									<div class="row">
										<div class="col s12 m6 l12">
										<h6><b>Comments</b></h6>
										</div>
									</div>
									<div id='ajaxComment'>
									</div>
								</div>
								<div class="col s12 m6 l3">
									<h5 class="large"><b>Add</b></h5>
									<div class="divider"></div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->activityAttachment == "1") || ($role == "Client" && $roleClient->activityAttachment == "1") )
										{
											echo '<div class="row roleActivityAttachment" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleActivityAttachment" style="margin-top:5px;display:none;">';
										}
									?>
									
										<a class="btn-flat dropdown-button waves-effect black-text" href="javascript:void(0);" data-activates="dropdownattachment">Attachment<i class="mdi-navigation-arrow-drop-down right"></i></a>
											<ul id="dropdownattachment" class="dropdown-content">
												<li>
													<div class="file-field input-field">
								                      <div class="btn-flat waves-effect">
								                        <span style="margin-left:-18%;">Computer</span>
								                        <input type="file" id="inputComputer" onchange="createAttachment()">
								                      </div>
								                      <div class="file-path-wrapper">
								                      </div>
								                    </div>
												</li>
												<li>
													<a href="javascript:void(0);" onclick="openGoogleDrive()" class="black-text left-align btn-flat waves-effect">Google Drive</a>
												</li>
												<li>
													<a href="javascript:void(0);" onclick="openDropbox()" class="black-text left-align btn-flat waves-effect">Dropbox</a>
												</li>
											</ul>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->activityAM == "1") || ($role == "Client" && $roleClient->activityAM == "1") )
										{
											echo '<div class="row roleActivityAM" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleActivityAM" style="margin-top:5px;display:none;">';
										}
									?>
									
										<a href="#modalassignmembers" class="modal-trigger btn-flat waves-effect" style="font-size:90%;">Assign Members</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->activityLabel == "1") || ($role == "Client" && $roleClient->activityLabel == "1") )
										{
											echo '<div class="row roleActivityLabel" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleActivityLabel" style="margin-top:5px;display:none;">';
										}
									?>
										<a href="#modallabelcard" class="modal-trigger btn-flat waves-effect">Label Card</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->activityChecklist == "1") || ($role == "Client" && $roleClient->activityChecklist == "1") )
										{
											echo '<div class="row roleActivityChecklist" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleActivityChecklist" style="margin-top:5px;display:none;">';
										}
									?>
										<a href="#modalchecklist" class="modal-trigger btn-flat waves-effect">Checklist</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->activityStartDate == "1") || ($role == "Client" && $roleClient->activityStartDate == "1") )
										{
											echo '<div class="row roleActivityStartDate" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleActivityStartDate" style="margin-top:5px;display:none;">';
										}
									?>
										<a href="#modalstartdate" class="modal-trigger btn-flat waves-effect">Start Date</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->activityDueDate == "1") || ($role == "Client" && $roleClient->activityDueDate == "1") )
										{
											echo '<div class="row roleActivityDueDate" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleActivityDueDate" style="margin-top:5px;display:none;">';
										}
									?>
										<a href="#modalduedate" class="modal-trigger btn-flat waves-effect">Due Date</a>
									</div>
									<h5 class="large"><b>Menu</b></h5>
									<div class="divider"></div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardEdit == "1") || ($role == "Client" && $roleClient->cardEdit == "1") )
										{
											echo '<div class="row roleEditCard" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleEditCard" style="margin-top:5px;display:none;">';
										}
									?>
									
										<a href="#modalmove" class="modal-trigger btn-flat waves-effect">Move</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listCreate == "1") || ($role == "Client" && $roleClient->listCreate == "1") )
										{
											echo '<div class="row roleCreateCard" style="margin-top:5px;">';
										}
										else
										{
											echo '<div class="row roleCreateCard" style="margin-top:5px;display:none;">';
										}
									?>
									
										<a href="#modalcopy" onclick="openModalCopy()" class="modal-trigger btn-flat waves-effect">Copy</a>
									</div>
									<?php
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardDelete == "1") || ($role == "Client" && $roleClient->cardDelete == "1") )
										{
											echo '<div id="changeArchive" class="row roleDeleteCard" style="margin-top:5px;">';
										}
										else
										{
											echo '<div id="changeArchive" class="row roleDeleteCard" style="margin-top:5px;display:none;">';
										}
									?>
									
										<a href="javascript:void(0);" class="btn-flat waves-effect" onclick="changeArchive()">Archive</a>
									</div>
									<div id="changeSend" style="display:none;">
										<div class="divider"></div>
										<?php
											if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardDelete == "1") || ($role == "Client" && $roleClient->cardDelete == "1") )
											{
												echo '<div class="row roleDeleteCard" style="margin-top:5px;">';
											}
											else
											{
												echo '<div class="row roleDeleteCard" style="margin-top:5px;display:none;">';
											}
										?>
										
											<a href="javascript:void(0);" class="btn-flat waves-effect" onclick="changeSend()">Send to Board</a>
										</div>
										<?php
											if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->cardDelete == "1") || ($role == "Client" && $roleClient->cardDelete == "1") )
											{
												echo '<div class="row roleDeleteCard" style="margin-top:5px;">';
											}
											else
											{
												echo '<div class="row roleDeleteCard" style="margin-top:5px;display:none;">';
											}
										?>
										
											<a href="javascript:void(0);" class="btn-flat waves-effect" onclick="changeDelete()">Delete</a>
										</div>
									</div>
								</div>
							</div>
					  </div>
					  <div class="modal-footer teal lighten-4">
						<a class="waves-effect waves-green btn-flat  modal-close">Close</a>
					  </div>
					</div>
					<!-- END OF MODAL ACTION CARD-->
					<div id="card-stats">
							<!-- LIST -->
							<?php
								foreach($boardList as $l)
								{
									if($l->listArchive == "0" && $l->listStatus == "1")
									{
										echo '<div class="colListUser" id="colList'.$l->listId.'" style="">';
										echo	'<div class="card">';
										echo		'<div class="card-content grey lighten-2 white-text" style="height:100%;">'; //warna list
							            echo            '<p class=" grey-text text-darken-4 truncate" style="font-weight:bold;font-size:150%;">'.$l->listTitle.'<a href="javascript:void(0);" onclick="openModalListMenu(\''.$l->listId.'\')" class="black-text"><i class="mdi-navigation-more-vert right"></i></a></p>';
							            echo 			'<div id="list'.$l->listId.'" class="listUser dropable sortable" style="height:100%;min-height:60px;width:100%;">';
										
										foreach($boardCard as $c)
										{
											if($c->cardListId == $l->listId && $c->cardArchive == "0" && $c->cardStatus == "1")
											{
												echo 			'<div class="dragable cDrag'.$c->cardId.' cardUser'.$c->cardListId.'" id="cDrag'.$c->cardId.'" style="width:100%;height:100%;">';
												echo			'<a id="card'.$c->cardId.'" href="javascript:void(0);" class="aCardUserLabel" onclick="ajaxModalCard(\''.$c->cardId.'\')">';
												echo				'<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">';
												echo 				"<div class='row cardUserLabel' id='labelCard".$c->cardId."' style='margin:auto;'>";
												foreach($boardLabelCard as $lc)
												{
													if($lc->cardId == $c->cardId)
													{	
														if($lc->labelRed == "true")
														{
															echo '<div class="task-cat red left-align red-text" style="width:45%;float:left;margin:2px;">';
															echo 'Blank Text';
															echo '</div>';
														}
														if($lc->labelYellow == "true")
														{
															echo '<div class="task-cat yellow left-align yellow-text" style="width:45%;float:left;margin:2px;">';
															echo 'Blank Text';
															echo '</div>';
														}
														if($lc->labelGreen == 'true')
														{
															echo '<div class="task-cat green left-align green-text" style="width:45%;float:left;margin:2px;">';
															echo 'Blank Text';
															echo '</div>';
														}
														if($lc->labelBlue == 'true')
														{
															echo '<div class="task-cat blue left-align blue-text" style="width:45%;float:left;margin:2px;">';
															echo 'Blank Text';
															echo '</div>';
														}
													}
												}

												echo 				'</div>';
												echo				'<div class="left-align black-text" style="word-wrap:break-word;" id="cardTitle'.$c->cardId.'">'.$c->cardTitle.'</div>';
												echo				'</div>';
												echo			'</a>';
												echo 			'</div>';
											}

										}
										echo 			'</div>';
										if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listCreate == "1") || ($role == "Client" && $roleClient->listCreate == "1") )
										{
											echo            '<div class="card-compare grey lighten-2 roleCreateCard" style="margin-top:8px;border-radius:5px;">';
										}
										else
										{
											echo            '<div class="card-compare grey lighten-2 roleCreateCard" style="margin-top:8px;border-radius:5px;display:none;">';
										}
				                        
			                            echo           		'<div id="invoice-line" class="left-align grey-text"><a href="javascript:void(0);" class="grey-text" onclick="setHiddenListId(\''.$l->listId.'\')">Add a Card..</a></div>';
			                            echo       		'</div>';

										echo		'</div>';
										echo	'</div>';
										echo '</div>';
									}
									
								}
								if($role == "Creator" || ($role == "Collaborator" && $roleCollaborator->listCreate == "1") || ($role == "Client" && $roleClient->listCreate == "1") )
								{
									echo '<div class="colListUser roleCreateList" style="" id="listCreateList">';
								}
								else
								{
									echo '<div class="colListUser roleCreateList" style="" id="listCreateList">';	
								}
								echo	'<div class="card">';
								echo		'<div class="card-content grey white-text">';
			                    echo           '<div class="card-compare  grey" style="margin-top:8px;border-radius:5px;">';
			                    echo           		'<div id="invoice-line" class="left-align white-text"><a href="javascript:void(0);" class="white-text">Add a List..</a></div>';
			                    echo       		'</div>';
								echo		'</div>';
								echo	'</div>';
								echo '</div>';
							?>
					</div>
				
				</div>





				<!-- Floating Action Button -->
				<div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
					<a class="btn-floating btn-large">
					  <i class="mdi-action-stars"></i>
					</a>
					<ul>
					  <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
					  <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
					  <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
					  <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
					</ul>
				</div>
				<!-- Floating Action Button -->
			</div>
			<!--end container-->
		</section>
		<!-- END CONTENT -->
		      <!-- START RIGHT SIDEBAR NAV-->
  	<aside id="right-sidebar-nav">
        <ul id="chat-out" class="side-nav rightside-navigation">
            <li class="li-hover">
            <a href="javascript:void(0);" data-activates="chat-out" class="chat-close-collapse right"><i class="mdi-navigation-close"></i></a>
            <div id="right-search" class="row">
                <div class="col s12">
                    <div class="input-field">
                        <i class="mdi-communication-chat prefix"></i>
                        <input id="chatText" type="text" class="validate">
                        <label for="chatText">Chat</label>
                    </div>
                        <a class="btn waves-effect waves-light green" id="sendChat">Send</a>
                </div>
            </div>
            </li>
            <li class="li-hover">
                <ul class="chat-collapsible" data-collapsible="expandable">
                <li>
                    <div class="collapsible-header red white-text active"><i class="mdi-action-stars"></i>Chat Board</div>
                    <div class="collapsible-body favorite-associates" id="ajaxChat">
                        
                    </div>
                    
                </li>
                </ul>
            </li>
        </ul>
    </aside>

	</div>
	<!-- END WRAPPER -->
</div>
<!-- END MAIN -->

<script>
//var myVar = setInterval(function(){ myTimer() }, 1000);

//document.getElementById("btnDropbox").appendChild(button);
</script>