<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">                      
				  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" width="32px" height="32px" style="border-radius:50%" /></a>
					</li>
				</ul>
				<!-- translation-button -->
				<ul id="translation-dropdown" class="dropdown-content">
				  <li>
					<a href="userProfile?userId=<?php echo $userProfile->userId ?>"><img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" width="32px" height="32px" alt="Profile" />  <span class="language-select">Profile</span></a>
				  </li>
				  <li>
					<a onclick="cekLogout()"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
				  </li>
				  
				</ul>
			</div>
		</nav>

		<!-- HORIZONTL NAV START-->
		 <nav id="horizontal-nav" class="white hide-on-med-and-down">
			<div class="nav-wrapper">                  
			  <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
				<li>
					<a href="<?php echo "board?id=".$boardId ?>" class="cyan-text">
						<i class="mdi-action-dashboard"></i>
						<span>Board</span>
					</a>
				</li> 
			  </ul>
			</div>
		  </nav>
		<!-- HORIZONTL NAV END-->
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav hide-on-large-only">
    <ul id="slide-out" class="side-nav leftside-navigation ">
        <li class="user-details cyan darken-2">
            <div class="row">
                <div class="col col s4 m4 l4">
                    <img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" alt="" class="circle responsive-img valign profile-image">
                </div>
                <div class="col col s8 m8 l8">
                    <a class="dropdown-button waves-effect waves-light profile-btn white-text" href="#" disabled><?php echo $userProfile->userName ?><i class="mdi-navigation-arrow-drop-down right"></i></a>
                </div>
            </div>
        </li>
        <li class="bold active"><a href="<?php echo "board?id=".$boardId ?>" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Board</a>
        </li>
        <div class="divider"></div>
        <li class="bold active"><a href="userProfile?userId=<?php echo $userProfile->userId ?>" class="waves-effect waves-cyan">Profile</a>
        </li>
        <li class="bold active"><a onclick="cekLogout()" class="waves-effect waves-cyan">Log Out</a>
        </li>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>
<!-- END LEFT SIDEBAR NAV-->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
	<!-- START WRAPPER -->
	<div class="wrapper">

		<!-- START CONTENT -->
		<section id="content">

			<!--start container-->
			<div class="container">
				<!-- trello start here -->
				
				<div class="section">
			        <div id="full-calendar">              
			          <div class="row">
			          	<div class="col s12 m4 l3">
		                  <div id='external-events'>    
		                    <h4 class="header">Note</h4>
		                    <div class='fc-event center-align' style="background-color:green;">Start Date</div>
		                    <div class='fc-event center-align' style="background-color:red;">Due Date</div>
		                    <div class='fc-event center-align' style="background-color:blue;">Both Date</div>
		                    <a id="authorize-button" href="javascript:void(0)" class="waves-effect waves-red btn left-align" style="font-weight:50%;">Sync with Google Calendar</a>
		                  </div>
		                </div>
			            <div class="col s12 m8 l9">
			            	<input type="hidden" id="hiddenBoardId" value="<?php echo $boardId?>">
			              <div id='calendar'></div>
			            </div>
			          </div>
			        </div>
			    </div>




				<!-- Floating Action Button -->
				<div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
					<a class="btn-floating btn-large">
					  <i class="mdi-action-stars"></i>
					</a>
					<ul>
					  <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
					  <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
					  <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
					  <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
					</ul>
				</div>
				<!-- Floating Action Button -->
			</div>
			<!--end container-->
		</section>
		<!-- END CONTENT -->
		      <!-- START RIGHT SIDEBAR NAV-->
  	<aside id="right-sidebar-nav">
        <ul id="chat-out" class="side-nav rightside-navigation">
            <li class="li-hover">
            <a href="#" data-activates="chat-out" class="chat-close-collapse right"><i class="mdi-navigation-close"></i></a>
            <div id="right-search" class="row">
                <form class="col s12">
                    <div class="input-field">
                        <i class="mdi-communication-chat prefix"></i>
                        <input id="icon_prefix" type="text" class="validate">
                        <label for="icon_prefix">Chat</label>
                    </div>
                </form>
            </div>
            </li>
            <li class="li-hover">
                <ul class="chat-collapsible" data-collapsible="expandable">
                <li>
                    <div class="collapsible-header red white-text active"><i class="mdi-action-stars"></i>Chat Board</div>
                    <div class="collapsible-body favorite-associates">
                        <div class="favorite-associate-list chat-out-list row">
                            <div class="col s4"><img src="images/user/user2.png" alt="" class="circle responsive-img online-user valign profile-image">
                            </div>
                            <div class="col s8">
                                <p>Michael</p>
                                <p class="place black-text">No?</p>
                                <p class="ultra-small grey-text lighten-3">just now</p>
                            </div>
                        </div>
                        <div class="favorite-associate-list chat-out-list row">
                            <div class="col s4"><img src="images/user/gerrard.png" alt="" class="circle responsive-img online-user valign profile-image">
                            </div>
                            <div class="col s8">
                                <p>Steven Gerrard</p>
                                <p class="place black-text">How are you?</p>
                                <p class="ultra-small grey-text lighten-3">5 minutes ago</p>
                            </div>
                        </div>
                    </div>
                    
                </li>
                </ul>
            </li>
        </ul>
    </aside>

	</div>
	<!-- END WRAPPER -->
</div>
<!-- END MAIN -->
<script async defer src="https://apis.google.com/js/api.js"
  onload="this.onload=function(){};handleClientLoad()"
  onreadystatechange="if (this.readyState === 'complete') this.onload()">
</script>