<!-- Start Page Loading -->
<div id="loader-wrapper">
	<div id="loader"></div>        
	<div class="loader-section section-left"></div>
	<div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">                      
				  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="images/user/gerrard.png" width="32px" height="32px" style="border-radius:50%" /></a>
					</li>
				</ul>
				<!-- translation-button -->
				<ul id="translation-dropdown" class="dropdown-content">
				  <li>
					<a href="#!"><img src="images/user/user2.png" width="32px" height="32px" alt="Profile" />  <span class="language-select">Profile</span></a>
				  </li>
				  <li>
					<a href="#!"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
				  </li>
				  
				</ul>
			</div>
		</nav>

		<!-- HORIZONTL NAV START-->
		 <nav id="horizontal-nav" class="white hide-on-med-and-down">
			<div class="nav-wrapper">                  
			  <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
				<li>
					<a href="home" class="cyan-text">
						<i class="mdi-action-dashboard"></i>
						<span>Home</span>
					</a>
				</li>
				<li>
					<a href="#modalinvite" class="cyan-text modal-trigger">
						<i class="mdi-social-person-add"></i>
						<span>Invite</span>
					</a>
				</li>
				<li>
					<a href="#modalcreatelist" class="cyan-text modal-trigger">
						<i class="mdi-action-list"></i>
						<span>Create List</span>
					</a>
				</li> 
				<li>
					<a href="#modalcreatecard" class="cyan-text modal-trigger">
						<i class="mdi-content-add"></i>
						<span>Create Card</span>
					</a>
				</li>
				<li>
					<a href="#" class="cyan-text chat-collapse " data-activates="chat-out" data-sidenav="right" data-closeonclick="false">
						<i class="mdi-communication-chat"></i>
						<span>Chat Board</span>
					</a>
				</li>
				<li>
					<a href="#modalcalendar" class="cyan-text modal-trigger">
						<i class="mdi-action-schedule"></i>
						<span>Calender Board</span>
					</a>
				</li>
				<li>
					<a href="app-email.html" class="cyan-text">
						<i class="mdi-navigation-more-horiz"></i>
						<span>More</span>
					</a>
				</li>
			  </ul>
			</div>
		  </nav>
		<!-- HORIZONTL NAV END-->
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
	<!-- START WRAPPER -->
	<div class="wrapper">

		<!-- START CONTENT -->
		<section id="content">

			<!--start container-->
			<div class="container">
				<!-- trello start here -->
				
				<div class="section">

			        <p class="caption"><a href="board">Bucket List</a> / Calendar Board</p>
			        <div class="divider"></div>
			        <div id="full-calendar">              
			          <div class="row">
			            <div class="col s12 m4 l3">
			              <div id='external-events'>    
			                <h4 class="header">Draggable Events</h4>
			                <div class='fc-event cyan'>March Invoices</div>
			                <div class='fc-event teal'>Call Emy</div>
			                <div class='fc-event cyan darken-1'>Dinner with Team</div>
			                <div class='fc-event cyan accent-4'>Meeting with Support Team</div>
			                <div class='fc-event teal accent-4'>Meeting with Sales Team</div>
			                <div class='fc-event light-blue accent-3'>Design an iOS App</div>
			                <div class='fc-event light-blue accent-4'>Company Party</div>
			                <p>
			                  <input type='checkbox' id='drop-remove' />
			                  <label for='drop-remove'>remove after drop</label>
			                </p>
			              </div>
			            </div>
			            <div class="col s12 m8 l9">
			              <div id='calendar'></div>
			            </div>
			          </div>
			        </div>
			    </div>




				<!-- Floating Action Button -->
				<div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
					<a class="btn-floating btn-large">
					  <i class="mdi-action-stars"></i>
					</a>
					<ul>
					  <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
					  <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
					  <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
					  <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
					</ul>
				</div>
				<!-- Floating Action Button -->
			</div>
			<!--end container-->
		</section>
		<!-- END CONTENT -->
		      <!-- START RIGHT SIDEBAR NAV-->
  	<aside id="right-sidebar-nav">
        <ul id="chat-out" class="side-nav rightside-navigation">
            <li class="li-hover">
            <a href="#" data-activates="chat-out" class="chat-close-collapse right"><i class="mdi-navigation-close"></i></a>
            <div id="right-search" class="row">
                <form class="col s12">
                    <div class="input-field">
                        <i class="mdi-communication-chat prefix"></i>
                        <input id="icon_prefix" type="text" class="validate">
                        <label for="icon_prefix">Chat</label>
                    </div>
                </form>
            </div>
            </li>
            <li class="li-hover">
                <ul class="chat-collapsible" data-collapsible="expandable">
                <li>
                    <div class="collapsible-header red white-text active"><i class="mdi-action-stars"></i>Chat Board</div>
                    <div class="collapsible-body favorite-associates">
                        <div class="favorite-associate-list chat-out-list row">
                            <div class="col s4"><img src="images/user/user2.png" alt="" class="circle responsive-img online-user valign profile-image">
                            </div>
                            <div class="col s8">
                                <p>Michael</p>
                                <p class="place black-text">No?</p>
                                <p class="ultra-small grey-text lighten-3">just now</p>
                            </div>
                        </div>
                        <div class="favorite-associate-list chat-out-list row">
                            <div class="col s4"><img src="images/user/gerrard.png" alt="" class="circle responsive-img online-user valign profile-image">
                            </div>
                            <div class="col s8">
                                <p>Steven Gerrard</p>
                                <p class="place black-text">How are you?</p>
                                <p class="ultra-small grey-text lighten-3">5 minutes ago</p>
                            </div>
                        </div>
                    </div>
                    
                </li>
                <li>
            	<div class="collapsible-header teal white-text"><i class="mdi-social-whatshot"></i>Recent Activites</div>
                    <div class="collapsible-body recent-activity">
                        <div class="recent-activity-list chat-out-list row">
                            <div class="col s3 recent-activity-list-icon"><i class="mdi-action-add-shopping-cart"></i>
                            </div>
                            <div class="col s9 recent-activity-list-text">
                                <a href="#">just now</a>
                                <p>Jim Doe Purchased new equipments for zonal office.</p>
                            </div>
                        </div>
                        <div class="recent-activity-list chat-out-list row">
                            <div class="col s3 recent-activity-list-icon"><i class="mdi-device-airplanemode-on"></i>
                            </div>
                            <div class="col s9 recent-activity-list-text">
                                <a href="#">Yesterday</a>
                                <p>Your Next flight for USA will be on 15th August 2015.</p>
                            </div>
                        </div>
                    </div>
                </li>
                </ul>
            </li>
        </ul>
    </aside>

	</div>
	<!-- END WRAPPER -->
</div>
<!-- END MAIN -->