<!-- START HEADER -->
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color">
            <div class="nav-wrapper">
                <ul class="left">                      
                  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
                </ul>
                <div class="header-search-wrapper hide-on-med-and-down">
                    <i class="mdi-action-search"></i>
                    <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
                </div>
                <ul class="right hide-on-med-and-down">
                    <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
                    </li>
                    <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src= "userImage/user.jpg" width="32px" height="32px" style="border-radius:50%" /></a>
                    </li>
                </ul>
                <!-- translation-button -->
                <ul id="translation-dropdown" class="dropdown-content">
                  <li>
                    <a onclick="cekLogout()"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
                  </li>
                  
                </ul>
            </div>
        </nav>

        <!-- HORIZONTL NAV START-->
         <nav id="horizontal-nav" class="white hide-on-med-and-down">
            <div class="nav-wrapper">                  
              <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
                <li>
                    <a href="muser" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master User</span>
                    </a>
                </li> 
                <li>
                    <a href="mgroup" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Group</span>
                    </a>
                </li>
                <li>
                    <a href="mboard" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Board</span>
                    </a>
                </li>  
              </ul>
            </div>
          </nav>
        <!-- HORIZONTL NAV END-->
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav hide-on-large-only">
    <ul id="slide-out" class="side-nav leftside-navigation ">
        <li class="bold active"><a href="muser" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master User</a>
        </li>
        <li class="bold active"><a href="mgroup" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Group</a>
        </li>
        <li class="bold active"><a href="mboard" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Board</a>
        </li>
        <div class="divider"></div>
        <li class="bold active"><a onclick="cekLogout()" class="waves-effect waves-cyan">Log Out</a>
        </li>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>
<!-- END LEFT SIDEBAR NAV-->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
    <!-- START WRAPPER -->
    <div class="wrapper">

        <!-- START CONTENT -->
        <section id="content">

            <!--start container-->
            <div class="container">
                <!-- trello start here -->
                
                <div class="section">
                    <div class="row">
                        <div class="col s12 m6 l6">
                            Board member
                            <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Member ID</th>
                                    <th>User ID</th>
                                    <th>Member Created</th>
                                    <th>Member Role</th>
                                    <th>Member Status</th>
                                    <th>Detail</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Member ID</th>
                                    <th>User ID</th>
                                    <th>Member Created</th>
                                    <th>Member Role</th>
                                    <th>Member Status</th>
                                    <th>Detail</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                <?php
                                    foreach($member as $m)
                                    {
                                        echo "<tr>";
                                        echo "<td>".$m->memberId."</td>";
                                        echo "<td>".$m->userId."</td>";
                                        echo "<td>".date_format(new DateTime($m->memberCreated),"d M Y")."</td>";
                                        echo "<td>".$m->memberRole."</td>";
                                        echo "<td>".$m->memberStatus."</td>";
                                        echo "<td><a onclick='detailMember(\"".$m->memberId."\")'>Detail</a></td>";
                                        echo "</tr>";
                                    }
                                ?>
                            </tbody>
                          </table>
                        </div>
                        <div class="col s12 m6 l6">
                            Detail Member
                            <div class="row">
                                <div class="input-field col s6">
                                  <input id="searchMemberId" type="text" class="">
                                  <label for="searchMemberId">Board ID</label>
                                </div>
                                <div class="input-field col s6">
                                <a onclick="searchMember()" class="waves-effect waves-light  btn">Search</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Member ID <input id="detailMemberId" type="text" class="" placeholder="Member ID" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  User ID <input id="detailUserId" type="text" class="" placeholder="User ID" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Member Created<input id="detailBoardTitle" type="text" placeholder="Member Created" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Member Role<input id="detailMemberRole" type="text" placeholder="Member Role" class="" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Member Status <input id="detailMemberStatus" type="text" placeholder="Member Status" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                <a onclick="saveMember()" class="waves-effect waves-light  btn">Save</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="divider"></div>
                    <div class="row">
                        <div class="col s12 m6 l6">
                            Board role collaborator
                        </div>
                        <div class="col s12 m6 l6">
                            Board role client
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 m6 l6">
                            Board progress deadline
                        </div>
                        <div class="col s12 m6 l6">
                            Board progress checklist
                        </div>
                    </div>
                    <div class="row">
                        Board Chat
                    </div>
                </div>
            </div>
            <!--end container-->
        </section>
        <!-- END CONTENT -->

    </div>
    <!-- END WRAPPER -->
</div>