<!-- START HEADER -->
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color">
            <div class="nav-wrapper">
                <ul class="left">                      
                </ul>
                <div class="header-search-wrapper hide-on-med-and-down">
                </div>
                <ul class="right hide-on-med-and-down">
                    <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
                    </li>
                    <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src= "userImage/user.jpg" width="32px" height="32px" style="border-radius:50%" /></a>
                    </li>
                </ul>
                <!-- translation-button -->
                <ul id="translation-dropdown" class="dropdown-content">
                  <li>
                    <a onclick="cekLogout()"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
                  </li>
                  
                </ul>
            </div>
        </nav>

        <!-- HORIZONTL NAV START-->
         <nav id="horizontal-nav" class="white hide-on-med-and-down">
            <div class="nav-wrapper">                  
              <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
                <li>
                    <a href="muser" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master User</span>
                    </a>
                </li> 
                <li>
                    <a href="mgroup" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Group</span>
                    </a>
                </li>
                <li>
                    <a href="mboard" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Board</span>
                    </a>
                </li>
                <li>
                    <a href="mlist" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master List</span>
                    </a>
                </li>   
                <li>
                    <a href="mcard" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Card</span>
                    </a>
                </li>
                <li>
                    <a href="repadmin" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Report</span>
                    </a>
                </li> 
              </ul>
            </div>
          </nav>
        <!-- HORIZONTL NAV END-->
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav hide-on-large-only">
    <ul id="slide-out" class="side-nav leftside-navigation ">
        <li class="bold active"><a href="muser" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master User</a>
        </li>
        <li class="bold active"><a href="mgroup" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Group</a>
        </li>
        <li class="bold active"><a href="mboard" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Board</a>
        </li>
        <li class="bold active"><a href="mlist" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master List</a>
        </li>
        <li class="bold active"><a href="mcard" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Card</a>
        </li>
        <li class="bold active"><a href="repadmin" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Report</a>
        </li>
        <div class="divider"></div>
        <li class="bold active"><a onclick="cekLogout()" class="waves-effect waves-cyan">Log Out</a>
        </li>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>
<!-- END LEFT SIDEBAR NAV-->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
    <!-- START WRAPPER -->
    <div class="wrapper">

        <!-- START CONTENT -->
        <section id="content">

            <!--start container-->
            <div class="container">
                <!-- trello start here -->
                
                <div class="section">
                    <div class="row">
                        <div class="col s12 m7 l8">
                          <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Board ID</th>
                                    <th>Board Owner</th>
                                    <th>Board Title</th>
                                    <th>Board Created</th>
                                    <th>Board Closed</th>
                                    <th>Board Group</th>
                                    <th>Board Status</th>
                                    <th>Board Background</th>
                                    <th>Detail</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Board ID</th>
                                    <th>Board Owner</th>
                                    <th>Board Title</th>
                                    <th>Board Created</th>
                                    <th>Board Closed</th>
                                    <th>Board Group</th>
                                    <th>Board Status</th>
                                    <th>Board Background</th>
                                    <th>Detail</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                <?php
                                    foreach($board as $b)
                                    {
                                        echo "<tr>";
                                        echo "<td>".$b->boardId."</td>";
                                        echo "<td>".$b->boardOwner."</td>";
                                        echo "<td>".$b->boardTitle."</td>";
                                        echo "<td>".date_format(new DateTime($b->boardCreated),"d M Y")."</td>";
                                        echo "<td>".$b->boardClosed."</td>";
                                        echo "<td>".$b->boardGroup."</td>";
                                        echo "<td>".$b->boardStatus."</td>";
                                        echo "<td>".$b->boardBackground."</td>";
                                        echo "<td><a onclick='detailBoard(\"".$b->boardId."\")'>Detail</a></td>";
                                        echo "</tr>";
                                    }
                                ?>
                            </tbody>
                          </table>
                        </div>
                        <div class="col s12 m5 l4">
                            <div class="row">
                                <div class="input-field col s6">
                                  <input id="searchBoardId" type="text" class="">
                                  <label for="searchBoardId">Board ID</label>
                                </div>
                                <div class="input-field col s6">
                                <a onclick="searchBoard()" class="waves-effect waves-light  btn">Search</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board ID <input id="detailBoardId" type="text" class="" placeholder="Board ID" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board Owner <input id="detailBoardOwner" type="text" class="" placeholder="Board Owner" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board Title<input id="detailBoardTitle" type="text" placeholder="Board Title" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board Created<input id="detailBoardCreated" type="text" placeholder="Board Created" class="" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board Closed <input id="detailBoardClosed" type="text" placeholder="Board Closed" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board Group <input id="detailBoardGroup" type="text" placeholder="Board Group" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board Status<input id="detailBoardStatus" type="text" placeholder="Board Status" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Board Background<input id="detailBoardBackground" type="text" placeholder="Board Background" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                <a onclick="saveBoard()" class="waves-effect waves-light  btn">Save</a>
                                </div>
                                <div class="input-field col s6">
                                <a onclick="checkBoard()" class="waves-effect waves-light blue btn">Check</a>
                                </div>
                            </div>

                        </div>
                        <div class="divider" style="margin:5px;"></div>
                        
                        <div class="row">
                            <h1>Insert Board</h1>
                            <div class="col s12 m12 l12">
                                <div class="row">
                                    <div class="input-field col s6">
                                      Board Title<input id="insertBoardTitle" type="text" placeholder="Board Title" class="">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6">
                                      <select id="insertUserId">
                                        <?php
                                            foreach($user as $u)
                                            {
                                                echo "<option value='".$u->userId."'>".$u->userId."</option>";
                                            }
                                        ?>
                                      </select>
                                      <select id="insertGroupId">
                                        <option value="B"></option>
                                        <?php
                                            foreach($group as $g)
                                            {
                                                echo "<option value='".$g->groupId."'>".$g->groupId."</option>";
                                            }
                                        ?>
                                      </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6">
                                    <a onclick="insertBoard()" class="waves-effect waves-light  green btn">Insert</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end container-->
        </section>
        <!-- END CONTENT -->

    </div>
    <!-- END WRAPPER -->
</div>