<!-- Start Page Loading -->
<div id="loader-wrapper">
	<div id="loader"></div>        
	<div class="loader-section section-left"></div>
	<div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">                      
				  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" width="32px" height="32px" style="border-radius:50%" /></a>
					</li>
				</ul>
				<!-- translation-button -->
				<ul id="translation-dropdown" class="dropdown-content">
				  <li>
					<a href="userProfile?userId=<?php echo $userId ?>"><img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" width="32px" height="32px" alt="Profile" />  <span class="language-select">Profile</span></a>
				  </li>
				  <li>
					<a onclick="cekLogout()"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
				  </li>
				  
				</ul>
			</div>
		</nav>

		<!-- HORIZONTL NAV START-->
		 <nav id="horizontal-nav" class="white hide-on-med-and-down">
			<div class="nav-wrapper">                  
			  <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
				<li>
					<a href="home" class="cyan-text">
						<i class="mdi-action-dashboard"></i>
						<span>Home</span>
					</a>
				</li>
				<li>
					<?php
						echo '<a href="#modalcreateboard" class="cyan-text modal-trigger" onclick="hiddenGroupId(\''.$userId.'\')">';
					?>
						<i class="mdi-action-note-add"></i>
						<span>Create Board</span>
					</a>
				</li> 
				<li>
					<a id="cokbesar" href="#modalcreategroup" class="modal-trigger cyan-text">
						<i class="mdi-social-group"></i>
						<span>Create Group Board</span>
					</a>
				</li>
				<li>
					<a href="#modalclosedboards" class="cyan-text modal-trigger">
						<i class="mdi-navigation-close"></i>
						<span>Closed Boards</span>
					</a>
				</li>
			  </ul>
			</div>
		  </nav>
		<!-- HORIZONTL NAV END-->
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->


<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav hide-on-large-only">
    <ul id="slide-out" class="side-nav leftside-navigation ">
        <li class="user-details cyan darken-2">
            <div class="row">
                <div class="col col s4 m4 l4">
                    <img src="<?php 
		                    if(strpos($userProfile->userImage,"userImage") !== false)
		                    {
		                   		echo $userProfile->userImage."?".filemtime($userProfile->userImage); 
		                    }
		                    else if(strpos($userProfile->userImage,"googleusercontent.com") !== false)
		                    {
		                    	echo $userProfile->userImage;
		                    }
		                    else
		                    {
		                    	echo "userImage/user.jpg";
		                    }

		                    ?>" alt="" class="circle responsive-img valign profile-image">
                </div>
                <div class="col col s8 m8 l8">
                    <a class="dropdown-button waves-effect waves-light profile-btn white-text" href="#" disabled><?php echo $userProfile->userName ?><i class="mdi-navigation-arrow-drop-down right"></i></a>
                </div>
            </div>
        </li>
        <li class="bold active"><a href="home" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Home</a>
        </li>
        <li class="bold active"><a href="#modalcreateboard" class="waves-effect waves-cyan modal-trigger"><i class="mdi-action-note-add"></i> Create Board</a>
        </li>
        <li class="bold active"><a href="#modalcreategroup" class="waves-effect waves-cyan modal-trigger"><i class="mdi-social-group"></i> Create Group Board</a>
        </li>
        <li class="bold active"><a href="#modalclosedboards" class="waves-effect waves-cyan modal-trigger"><i class="mdi-navigation-close"></i> Closed Boards</a>
        </li>
        <div class="divider"></div>
        <li class="bold active"><a href="#" class="waves-effect waves-cyan">Profile</a>
        </li>
        <li class="bold active"><a href="#" class="waves-effect waves-cyan">Log Out</a>
        </li>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>
<!-- END LEFT SIDEBAR NAV-->



<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
	<!-- START WRAPPER -->
	<div class="wrapper">

		<!-- START CONTENT -->
		<section id="content">

			<!--start container-->
			<div class="container">
				<div class="section">
					<div id="modalcreateboard" class="modal">
		                  <div class="modal-content">
		                    <div class="col s12 m6 l12">
		                    	<div class="row">
		                    		<h6><b>Create a board..</b></h6>
		                    		<div class="divider"></div>
		                    		<p>Title</p>
		                    		<input type="text" placeholder="Title.." id="boardTitle">
		                    		<input type="hidden" id="hiddenOwnerId">
		                    	</div>
		                    </div>
		                  </div>
		                  <div class="modal-footer">
		                    <a class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
		                  	<a onclick="createBoard()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
		                  </div>
	                </div>
	                <div id="modalcreategroup" class="modal">
		                  <div class="modal-content">
		                    <div class="col s12 m6 l12">
		                    	<div class="row">
		                    		<h6><b>Create a group board..</b></h6>
		                    		<div class="divider"></div>
		                    		<p>Name</p>
		                    		<input type="text" placeholder="Name.." id="groupName">
		                    	</div>
		                    </div>
		                  </div>
		                  <div class="modal-footer">
		                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
		                  	<a onclick="createGroup()" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
		                  </div>
	                </div>
	                <div id="modalclosedboards" class="modal">
		                  <div class="modal-content">
		                    <div class="col s12 m6 l12">
		                    	<div class="row">
		                    		<h6><b>Closed boards..</b></h6>
		                    		<div class="divider"></div>
		                    		<div class="col s12 m6 l12">
		                    			<p><b>Boards</b></p>
		                    			<div class="divider"></div>
		                    			<p>Board Satu <a href="#" class="ultra-small green-text">Re-open </a><a href="#" class="ultra-small red-text">Delete</a></p>
		                    			<p>Board Dua <a href="#" class="ultra-small green-text">Re-open </a><a href="#" class="ultra-small red-text">Delete</a></p>
		                    		</div>
		                    	</div>
		                    </div>
		                  </div>
		                  <div class="modal-footer">
		                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
		                  </div>
	                </div>
	                <div class="col s12 m4 l8">
							<p><b>Filter Board</b></p>
							<input type="checkbox" id="filterred" />
	                      	<label for="filterred"><div style="background-color:red;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filteryellow" />
	                      	<label for="filteryellow"><div style="background-color:yellow;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filtergreen" />
	                      	<label for="filtergreen"><div style="background-color:green;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filterblue" />
	                      	<label for="filterblue"><div style="background-color:blue;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
					</div>
					<div class="divider"></div>
					<p class="caption"><img src="images/user/star.png" width="20px" height="20px" alt="Profile" /> <b>Favorite Boards</b></p>
                    <div id="card-stats">
                        <div class="row">
                            <div class="col s12 m6 l3">
                                <div class="card">
                                    <a href="#" class="secondary-content yellow"><i class="mdi-action-grade"></i></a>
                                    <div class="card-content  green white-text">
                                        <h2 class="card-stats-title">Life Goals</h2>
                                        
                                    </div>
                                    <div class="card-action  green darken-2">
                                        <div id="invoice-line" class="center-align">Today</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="divider"></div>
	            	<p class="caption"><img src="images/user/user5.png" width="20px" height="20px" alt="Profile" /><b> My Boards</b></p>
                    
                	<?php
                		echo '<div id="card-stats">';
               			echo '<div class="row">';
               			echo '<div id="ajaxBoard'.$userId.'" style="margin-top:-25px;">';
                		foreach($board as $r)
                		{	
                			if($r->boardOwner == $userId)
                			{
                				if($r->boardGroup == "0")
                				{

		                			echo '<div class="col s12 m6 l3">';
		                			echo '<a href="board?id='.$r->boardId.'" >';
		                    		echo 	'<div class="card">';
		                    		echo 		'<div class="secondary-content yellow"><i class="mdi-action-grade"></i></div>';
		                            echo    	'<div class="card-content '.$r->boardBackground.' white-text">';
		                            echo       		'<h2 class="card-stats-title">'.$r->boardTitle.'</h2>';      
		                            echo   		'</div>';
		                            echo    	'<div class="card-action '.$r->boardBackground.' darken-2">';
		                            echo        	'<div id="invoice-line" class="center-align black-text">'.date_format(new DateTime($r->boardCreated),"d M Y").'</div>';
		                            echo    	'</div>';
		                    		echo 	'</div>';
		                    		echo '</a>';
		                    		echo '</div>';
                				}
                			}
                    		//date_format($r->boardCreated,"d/M/Y");
                		}
                		echo '</div>';
                			
                        echo '<div class="col s12 m6 l3">';
                        echo     '<div class="card">';
                        echo        '<div class="card-content grey white-text">';
                        echo 			'<a href="#modalcreateboard" class="modal-trigger" onclick="hiddenGroupId(\''.$userId.'\')">';
                        echo            '<h2 class="card-stats-title white-text">Create a new Board..</h2>';
                        echo            '</a>';
                        echo        '</div>';
                        echo    '</div>';
                        echo '</div>';
                    	//echo '<div class="divider"></div>';
                    	echo '</div>';
                    	echo '</div>';
            			echo '<div class="divider"></div>';
                	?>
                		<div id="ajaxGroup">
	            	<?php

	            		foreach($groupMember as $r) //mendapatkan list group yang terdapat user
	            		{
	            			$groupName = "";
	            			foreach($groupUser as $g) //mendapatkan nama group
	            			{
	            				if($r->groupUserId == $g->groupId)
	            				{
	            					$groupName = $g->groupName;
	            				}
	            			}
	            			echo '<p class="caption"><img src="images/user/group.png" width="20px" height="20px" alt="Profile" /><a href="#" class="black-text"> <b>'.$groupName.'</b> </a></p>';
            				echo '<div id="card-stats">';
	                     	echo   '<div class="row">';
	                     	echo '<div id="ajaxBoard'.$r->groupUserId.'" style="margin-top:-25px;">';
			                foreach($boardGroup as $g)
			                {
			                	if($g->groupId == $r->groupUserId)
			                	{
			                		foreach($board as $b)
			                		{
			                			if($b->boardId == $g->boardId)
			                			{
											echo    	'<div class="col s12 m6 l3">';
					                        echo 			'<a href="board?id='.$b->boardId.'" >';
					                        echo        	'<div class="card">';
					                        echo            	'<div class="card-content red white-text">';
					                        echo                	'<h2 class="card-stats-title">'.$b->boardTitle.'</h2>';
					                        echo            	'</div>';
					                        echo            	'<div class="card-action red darken-2">';
					                        echo              	  '<div id="invoice-line" class="center-align black-text">'.date_format(new DateTime($b->boardCreated),"d M Y").'</div>';
					                        echo           	 	'</div>';
					                        echo       	 	'</div>';
					                        echo 			'</a>';
					                        echo   	 	'</div>';
			                			}
			                		}
			                	}
			                }
			                echo '</div>';
		            		

	                        echo    	'<div class="col s12 m6 l3">';
	                        echo        	'<div class="card">';
	                        echo            	'<div class="card-content grey white-text">';
	                        echo 						'<a href="#modalcreateboard" class="modal-trigger" onclick="hiddenGroupId(\''.$r->groupUserId.'\')">';
	                        echo                		'<h2 class="card-stats-title white-text">Create a new Board..</h2>';
	                        echo                	'</a>';
	                        echo            	'</div>';
	                        echo        	'</div>';
	                        echo    	'</div>';
	                        echo 	'</div>';
	                   		echo '</div>';
	                   		echo "<div class='divider'></div>";
	            		}
	            	?>
	            	</div>
            	</div>







				<!-- Floating Action Button -->
				<div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
					<a class="btn-floating btn-large">
					  <i class="mdi-action-stars"></i>
					</a>
					<ul>
					  <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
					  <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
					  <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
					  <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
					</ul>
				</div>
				<!-- Floating Action Button -->
			</div>
			<!--end container-->
		</section>
		<!-- END CONTENT -->


	</div>
	<!-- END WRAPPER -->

</div>
<!-- END MAIN -->