<!-- Start Page Loading -->
<div id="loader-wrapper">
	<div id="loader"></div>        
	<div class="loader-section section-left"></div>
	<div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">                      
				  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="images/user/gerrard.png" width="32px" height="32px" style="border-radius:50%" /></a>
					</li>
				</ul>
				<!-- translation-button -->
				<ul id="translation-dropdown" class="dropdown-content">
				  <li>
					<a href="#!"><img src="images/user/user2.png" width="32px" height="32px" alt="Profile" />  <span class="language-select">Profile</span></a>
				  </li>
				  <li>
					<a href="#!"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
				  </li>
				  
				</ul>
			</div>
		</nav>

		<!-- HORIZONTL NAV START-->
		 <nav id="horizontal-nav" class="white hide-on-med-and-down">
			<div class="nav-wrapper">                  
			  <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
				<li>
					<a href="index.html" class="cyan-text">
						<i class="mdi-action-dashboard"></i>
						<span>Home</span>
					</a>
				</li>
				<li>
					<a href="app-email.html" class="cyan-text">
						<i class="mdi-action-note-add"></i>
						<span>Create Board</span>
					</a>
				</li> 
				<li>
					<a href="app-email.html" class="cyan-text">
						<i class="mdi-social-group"></i>
						<span>Create Group Board</span>
					</a>
				</li>
				<li>
					<a href="app-email.html" class="cyan-text">
						<i class="mdi-navigation-close"></i>
						<span>Closed Boards</span>
					</a>
				</li>
			  </ul>
			</div>
		  </nav>
		<!-- HORIZONTL NAV END-->
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
	<!-- START WRAPPER -->
	<div class="wrapper">

		<!-- START CONTENT -->
		<section id="content">

			<!--start container-->
			<div class="container">
				<div class="section">
					<p class="caption"><img src="images/user/star.png" width="20px" height="20px" alt="Profile" /> Favorite Boards</p>
                    <div id="card-stats">
                        <div class="row">
                            <div class="col s12 m6 l3">
                                <div class="card">
                                    <a href="#" class="secondary-content yellow"><i class="mdi-action-grade"></i></a>
                                    <div class="card-content  green white-text">
                                        <h2 class="card-stats-title">Life Goals</h2>
                                        
                                    </div>
                                    <div class="card-action  green darken-2">
                                        <div id="invoice-line" class="center-align">Today</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="divider"></div>
	            	<p class="caption"><img src="images/user/user5.png" width="20px" height="20px" alt="Profile" /> My Boards</p>
                    <div id="card-stats">
                        <div class="row">
                            <div class="col s12 m6 l3">
                                <div class="card">

                                    <a href="#" class="secondary-content yellow"><i class="mdi-action-grade"></i></a>
                                    <div class="card-content  green white-text">
                                        <h2 class="card-stats-title">Life Goals</h2>
                                        
                                    </div>
                                    <div class="card-action  green darken-2">
                                        <div id="invoice-line" class="center-align">Today</div>
                                    </div>
                                </div>
                            </div>
                       		<div class="col s12 m6 l3">
                                <div class="card">
                                    <div class="card-content  blue white-text">
                                        <h2 class="card-stats-title">Bucket List</h2>
                                        
                                    </div>
                                    <div class="card-action  blue darken-2">
                                        <div id="invoice-line" class="center-align">Yesterday</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col s12 m6 l3">
                                <div class="card">
                                    <div class="card-content grey white-text">
                                        <h2 class="card-stats-title">Create a new Board..</h2>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>




	            	<div class="divider"></div>
	            	<p class="caption"><img src="images/user/group.png" width="20px" height="20px" alt="Profile" /> STTS 2017 </p>
                    <div id="card-stats">
                        <div class="row">
                            <div class="col s12 m6 l3">
                                <div class="card">
                                    <div class="card-content red white-text">
                                        <h2 class="card-stats-title">Praktikum</h2>
                                    </div>
                                    <div class="card-action red darken-2">
                                        <div id="invoice-line" class="center-align">Last Week</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col s12 m6 l3">
                                <div class="card">
                                    <div class="card-content grey white-text">
                                        <h2 class="card-stats-title">Create a new Board..</h2>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            	</div>







				<!-- Floating Action Button -->
				<div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
					<a class="btn-floating btn-large">
					  <i class="mdi-action-stars"></i>
					</a>
					<ul>
					  <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
					  <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
					  <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
					  <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
					</ul>
				</div>
				<!-- Floating Action Button -->
			</div>
			<!--end container-->
		</section>
		<!-- END CONTENT -->


	</div>
	<!-- END WRAPPER -->

</div>
<!-- END MAIN -->