<body>
    <input type="hidden" id="hiddenBoardId" value="<?php echo $boardId;?>">
    <input type="hidden" id="hiddenCardId" value="<?php echo $cardId?>">
    <script type="text/javascript" src="js/plugins/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="js/myjs/jsDrive.js"></script>
    <script type="text/javascript" src="https://apis.google.com/js/api.js?onload=loadPicker"></script>
</body>