<!-- START HEADER -->
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color">
            <div class="nav-wrapper">
                <ul class="left">                      
                </ul>
                <div class="header-search-wrapper hide-on-med-and-down">
                </div>
                <ul class="right hide-on-med-and-down">
                    <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
                    </li>
                    <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src= "userImage/user.jpg" width="32px" height="32px" style="border-radius:50%" /></a>
                    </li>
                </ul>
                <!-- translation-button -->
                <ul id="translation-dropdown" class="dropdown-content">
                  <li>
                    <a onclick="cekLogout()"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
                  </li>
                  
                </ul>
            </div>
        </nav>

        <!-- HORIZONTL NAV START-->
         <nav id="horizontal-nav" class="white hide-on-med-and-down">
            <div class="nav-wrapper">                  
              <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
                <li>
                    <a href="muser" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master User</span>
                    </a>
                </li> 
                <li>
                    <a href="mgroup" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Group</span>
                    </a>
                </li>
                <li>
                    <a href="mboard" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Board</span>
                    </a>
                </li> 
                <li>
                    <a href="mlist" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master List</span>
                    </a>
                </li>
                <li>
                    <a href="mcard" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Master Card</span>
                    </a>
                </li>
                <li>
                    <a href="repadmin" class="cyan-text">
                        <i class="mdi-action-dashboard"></i>
                        <span>Report</span>
                    </a>
                </li>
              </ul>
            </div>
          </nav>
        <!-- HORIZONTL NAV END-->
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav hide-on-large-only">
    <ul id="slide-out" class="side-nav leftside-navigation ">
        <li class="bold active"><a href="muser" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master User</a>
        </li>
        <li class="bold active"><a href="mgroup" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Group</a>
        </li>
        <li class="bold active"><a href="mboard" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Board</a>
        </li>
        <li class="bold active"><a href="mlist" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master List</a>
        </li>
        <li class="bold active"><a href="mcard" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Master Card</a>
        </li>
        <li class="bold active"><a href="repadmin" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Report </a>
        </li>
        <div class="divider"></div>
        <li class="bold active"><a onclick="cekLogout()" class="waves-effect waves-cyan">Log Out</a>
        </li>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>
<!-- END LEFT SIDEBAR NAV-->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
    <!-- START WRAPPER -->
    <div class="wrapper">

        <!-- START CONTENT -->
        <section id="content">

            <!--start container-->
            <div class="container">
                <!-- trello start here -->
                
                <div class="section">
                    <div class="row">
                        <div class="col s12 m7 l8">
                          <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Group ID</th>
                                    <th>Group Name</th>
                                    <th>Group Created</th>
                                    <th>Group Status</th>
                                    <th>Detail</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Group ID</th>
                                    <th>Group Name</th>
                                    <th>Group Created</th>
                                    <th>Group Status</th>
                                    <th>Detail</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                <?php
                                    foreach($group as $g)
                                    {
                                        echo "<tr>";
                                        echo "<td>".$g->groupId."</td>";
                                        echo "<td>".$g->groupName."</td>";
                                        echo "<td>".date_format(new DateTime($g->groupCreated),"d M Y")."</td>";
                                        echo "<td>".$g->groupStatus."</td>";
                                        echo "<td><a onclick='detailGroup(\"".$g->groupId."\")'>Detail</a></td>";
                                        echo "</tr>";
                                    }
                                ?>
                            </tbody>
                          </table>
                        </div>
                        <div class="col s12 m5 l4">
                            <div class="row">
                                <div class="input-field col s6">
                                  <input id="searchGroupId" type="text" class="">
                                  <label for="searchGroupId">Group ID</label>
                                </div>
                                <div class="input-field col s6">
                                <a onclick="searchGroup()" class="waves-effect waves-light  btn">Search</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Group ID <input id="detailGroupId" type="text" class="" placeholder="Group ID" disabled>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Group Name <input id="detailGroupName" type="text" class="" placeholder="Group Name">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Group Description<input id="detailGroupDescription" type="text" placeholder="Group Description" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Group Website<input id="detailGroupWebsite" type="text" placeholder="Group Website" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Group Location <input id="detailGroupLocation" type="text" placeholder="Group Location" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  Group Status<input id="detailGroupStatus" type="text" placeholder="Grou Status" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                <a onclick="saveGroup()" class="waves-effect waves-light  btn">Save</a>
                                </div>
                            </div>

                        </div>

                    </div>
                    <div class="divider" style="margin:5px;"></div>
                    <div class="row">
                        <h1>Insert Group</h1>
                        <div class="col s12 m12 l12">
                            <div class="row">
                                <div class="input-field col s6">
                                  Group Name<input id="insertGroupName" type="text" placeholder="Group Name" class="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                  <select id="insertUserId">
                                    <?php
                                        foreach($user as $u)
                                        {
                                            echo "<option value='".$u->userId."'>".$u->userId."</option>";
                                        }
                                    ?>
                                  </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                <a onclick="insertGroup()" class="waves-effect waves-light  green btn">Insert</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="divider" style="margin:5px;"></div>
                    <div class="row">
                        <h1>Group Member</h1>
                        <div class="col s12 m12 l12">
                            <div class="row">
                                <div class="input-field col s6">
                                    <select id="memberGroupId"  onchange="getMemberByGroupId()">
                                    <?php
                                        foreach($group as $g)
                                        {
                                            echo "<option value='".$g->groupId."'>".$g->groupId."</option>";
                                        }
                                    ?>
                                  </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    Insert Member
                                    <select id="insertMemberUserId">
                                    <?php
                                        foreach($user as $u)
                                        {
                                            echo "<option value='".$u->userId."'>".$u->userId."</option>";
                                        }
                                    ?>
                                  </select>
                                  <a onclick="insertMember()" class="waves-effect waves-light  green btn">Insert</a>
                                </div>
                                <div class="input-field col s6">
                                    Remove Member
                                    <select id="removeMemberUserId" class="select-dropdown browser-default">
                                        <option value=""></option>
                                    </select>
                                    <a style="margin-top:10px;" onclick="removeMember()" class="waves-effect waves-light  red btn">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end container-->
        </section>
        <!-- END CONTENT -->

    </div>
    <!-- END WRAPPER -->
</div>