
<div id="login-page" class="row">
  <div class="col s12 z-depth-4 card-panel">
    <form class="login-form">
      <div class="row">
        <div class="input-field col s12 center">
          <img src="images/login-logo.png" alt="" class="circle responsive-img valign profile-image-login">
          <p class="center login-form-text">Material Design Admin Template</p>
        </div>
      </div>
      <div class="row margin">
        <div class="input-field col s12">
          <i class="mdi-social-person-outline prefix"></i>
          <input id="email" type="email">
          <label for="email" class="center-align">Email</label>
        </div>
        <div class="col s12" style="margin-left:15%;margin-top:-5%;display:none;" id="errorEmail">
            <label class="center-align red-text">Email required.</label>
        </div>
      </div>
      <div class="row margin">
        <div class="input-field col s12">
          <i class="mdi-action-lock-outline prefix"></i>
          <input id="password" type="password">
          <label for="password">Password</label>
        </div>
        <div class="col s12" style="margin-left:15%;margin-top:-5%;display:none;" id="errorPass">
            <label class="center-align red-text">Password required.</label>
        </div>
      </div>
      <div class="row">          
        <div class="input-field col s12 m12 l12  login-text">
            <input type="checkbox" id="remember" />
            <label for="remember">Remember me</label>
        </div>
      </div>
      <div class="row">

        <div class="col s12" style="display:none;" id="errorLogin">
            <label class="center-align red-text">Incorrect email and password.</label>
        </div>
        <div class="input-field col s12">
          <a class="btn waves-effect waves-light col s12" onclick="cekLogin()">Login</a>
        </div>
      </div>
      <div class="divider"></div>
      <div class="row">
        <div class="input-field col s12">
          <div id="my-signin2" onclick="googleLogin()"></div>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6 m6 l12">
          <p class="margin medium-small">Don't have an account yet? <a href="register">Register now!</a></p>
        </div>        
      </div>

    </form>
  </div>
</div>

