<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">                      
				  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					
				</ul>
			</div>
		</nav>
		 <nav id="horizontal-nav" class="white hide-on-med-and-down">
			<div class="nav-wrapper">                  
			  
			</div>
		  </nav>
	</div>
</header>

<aside id="left-sidebar-nav hide-on-large-only">
    
</aside>

<!-- START MAIN -->
<div id="main">
	<div class="wrapper">
		<section id="content">
			<div class="container">
				<div class="section">
				</div>
					<div id="card-stats">
					    <?php
					        echo '<div class="colListUser" id="colListDeparture" style="">';
							echo	'<div class="card">';
							echo		'<div class="card-content grey lighten-2 white-text" style="height:100%;">'; //warna list
				            echo            '<p class=" grey-text text-darken-4 truncate" style="font-weight:bold;font-size:150%;">'."Departure".'<a href="javascript:void(0);" onclick="" class="black-text"><i class="mdi-navigation-more-vert right"></i></a></p>';
				            echo 			'<div id="listDeparture" class="listUser dropable sortable" style="height:100%;min-height:60px;width:100%;">';
							
									echo 			'<div class="dragable cDrag'.'Static'.' cardUser'.'Departure'.'" id="cDrag'.'Static'.'" style="width:100%;height:100%;">';
									echo			'<a id="card'.'Static'.'" href="javascript:void(0);" class="aCardUserLabel" onclick="">';
									echo				'<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">';
									echo 				"<div class='row cardUserLabel' id='labelCard".'Static'."' style='margin:auto;'>";
									echo 				'</div>';
									echo				'<div class="left-align black-text" style="word-wrap:break-word;" id="cardTitle'.'Static'.'">'.'Static'.'</div>';
									echo				'</div>';
									echo			'</a>';
									echo 			'</div>';
								
							echo 			'</div>';
	                        echo            '<div class="card-compare grey lighten-2 roleCreateCard" style="margin-top:8px;border-radius:5px;display:none;">';
                            echo           		'<div id="invoice-line" class="left-align grey-text"><a href="javascript:void(0);" class="grey-text" onclick="">Add a Card..</a></div>';
                            echo       		'</div>';

							echo		'</div>';
							echo	'</div>';
							echo '</div>';
							
							echo '<div class="colListUser" id="colListDestination" style="">';
							echo	'<div class="card">';
							echo		'<div class="card-content grey lighten-2 white-text" style="height:100%;">'; //warna list
				            echo            '<p class=" grey-text text-darken-4 truncate" style="font-weight:bold;font-size:150%;">'."Destination".'<a href="javascript:void(0);" onclick="" class="black-text"><i class="mdi-navigation-more-vert right"></i></a></p>';
				            echo 			'<div id="listDestination" class="listUser dropable sortable" style="height:100%;min-height:60px;width:100%;">';
							
							echo 			'</div>';
	                        echo            '<div class="card-compare grey lighten-2 roleCreateCard" style="margin-top:8px;border-radius:5px;display:none;">';
                            echo           		'<div id="invoice-line" class="left-align grey-text"><a href="javascript:void(0);" class="grey-text" onclick="">Add a Card..</a></div>';
                            echo       		'</div>';

							echo		'</div>';
							echo	'</div>';
							echo '</div>';
					    ?>
					</div>
				</div>
			</div>
		</section>

	</div>
	<!-- END WRAPPER -->
</div>
<!-- END MAIN -->