<!-- Start Page Loading -->
<div id="loader-wrapper">
	<div id="loader"></div>        
	<div class="loader-section section-left"></div>
	<div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">                      
				  <li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Find Boards"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="images/user/gerrard.png" width="32px" height="32px" style="border-radius:50%" /></a>
					</li>
				</ul>
				<!-- translation-button -->
				<ul id="translation-dropdown" class="dropdown-content">
				  <li>
					<a href="#!"><img src="images/user/user2.png" width="32px" height="32px" alt="Profile" />  <span class="language-select">Profile</span></a>
				  </li>
				  <li>
					<a href="#!"><img src="images/user/logout.png" width="32px" height="32px" alt="French" />  <span class="language-select">Log Out</span></a>
				  </li>
				  
				</ul>
			</div>
		</nav>

		<!-- HORIZONTL NAV START-->
		 <nav id="horizontal-nav" class="white hide-on-med-and-down">
			<div class="nav-wrapper">                  
			  <ul id="ul-horizontal-nav" class="left hide-on-med-and-down">
				<li>
					<a href="home" class="cyan-text">
						<i class="mdi-action-dashboard"></i>
						<span>Home</span>
					</a>
				</li>
				<li>
					<a href="#modalinvite" class="cyan-text modal-trigger">
						<i class="mdi-social-person-add"></i>
						<span>Invite</span>
					</a>
				</li>
				<li>
					<a href="#modalcreatelist" class="cyan-text modal-trigger">
						<i class="mdi-action-list"></i>
						<span>Create List</span>
					</a>
				</li> 
				<li>
					<a href="#modalcreatecard" class="cyan-text modal-trigger">
						<i class="mdi-content-add"></i>
						<span>Create Card</span>
					</a>
				</li>
				<li>
					<a href="#" class="cyan-text chat-collapse " data-activates="chat-out" data-sidenav="right" data-closeonclick="false">
						<i class="mdi-communication-chat"></i>
						<span>Chat Board</span>
					</a>
				</li>
				<li>
					<a href="calendar" class="cyan-text">
						<i class="mdi-action-schedule"></i>
						<span>Calender Board</span>
					</a>
				</li>
				<li>
					<a href="#modalmore" class="cyan-text modal-trigger">
						<i class="mdi-navigation-more-horiz"></i>
						<span>More</span>
					</a>
				</li>
			  </ul>
			</div>
		  </nav>
		<!-- HORIZONTL NAV END-->
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav hide-on-large-only">
    <ul id="slide-out" class="side-nav leftside-navigation ">
        <li class="user-details cyan darken-2">
            <div class="row">
                <div class="col col s4 m4 l4">
                    <img src="images/user/gerrard.png" alt="" class="circle responsive-img valign profile-image">
                </div>
                <div class="col col s8 m8 l8">
                    <a class="dropdown-button waves-effect waves-light profile-btn white-text" href="#" disabled>Steven Gerrard<i class="mdi-navigation-arrow-drop-down right"></i></a>
                </div>
            </div>
        </li>
        <li class="bold active"><a href="home" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Home</a>
        </li>
        <li class="bold active"><a href="#modalinvite" class="waves-effect waves-cyan modal-trigger"><i class="mdi-social-person-add"></i>Invite</a>
        </li>
        <li class="bold active"><a href="#modalcreatelist" class="waves-effect waves-cyan modal-trigger"><i class="mdi-action-list"></i> Create List</a>
        </li>
        <li class="bold active"><a href="#modalcreatecard" class="waves-effect waves-cyan modal-trigger"><i class="mdi-content-add"></i> Create Card</a>
        </li>
        <li class="bold active"><a href="#" class="cyan-text chat-collapse " data-activates="chat-out" data-sidenav="right" data-closeonclick="false"><i class="mdi-communication-chat"></i>Chat Board</a>
        </li>
        <li class="bold active"><a href="calender" class="waves-effect waves-cyan"><i class="mdi-action-schedule"></i> Calender Board</a>
        </li>
        <li class="bold active"><a href="#modalmore" class="waves-effect waves-cyan modal-trigger"><i class="mdi-navigation-more-horiz"></i> More</a>
        </li>
        <div class="divider"></div>
        <li class="bold active"><a href="#" class="waves-effect waves-cyan">Profile</a>
        </li>
        <li class="bold active"><a href="#" class="waves-effect waves-cyan">Log Out</a>
        </li>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>
<!-- END LEFT SIDEBAR NAV-->




<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
	<!-- START WRAPPER -->
	<div class="wrapper">

		<!-- START CONTENT -->
		<section id="content">

			<!--start container-->
			<div class="container">
				<!-- trello start here -->
				<div class="section">
					<!-- BOARD -->
					<div class="row">
						<div class="col s6 m4 l4">
							<h1><b>Bucket List</b></h1>
						</div>
						<div class="col s6 m4 l8">
							<p>Filter Card</p>
							<input type="checkbox" id="filterred" />
	                      	<label for="filterred"><div style="background-color:red;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filteryellow" />
	                      	<label for="filteryellow"><div style="background-color:yellow;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filtergreen" />
	                      	<label for="filtergreen"><div style="background-color:green;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
                      		<input type="checkbox" id="filterblue" />
	                      	<label for="filterblue"><div style="background-color:blue;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
						</div>
					</div>
				</div>
					<div id="card-stats">
						<div class="row" style="display:flex;flex-wrap:wrap;">
							<!-- LIST -->
							<div class="col s12 m6 l2">
								<div class="card">
									<!-- MODAL MENU BOARD-->
									<div id="modalinvite" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<div class="col s12 m6 l6">
					                    			<p><b>Invite</b></p>
					                    			<input type="email" placeholder="Email">
					                    		</div>
					                    		<div class="col s12 m6 l6">
					                    			<p><b>Invited Members</b></p>
					                    			<p>michaelchandrag114@yahoo.co.id</p>
					                    			<p>canzinzzide@gmail.com</p>
					                    		</div>
					                    		<div class="col s12 m6 l12">
					                    			<p><b>Members</b></p>
					                    			<div class="row">
						                    			<div class="col s12 m4 l1">
	              		                          			<img src="images/user/gerrard.png" style="border-radius:50%;" width="32px" height="32px" alt="Profile" />
	              		                          		</div>
	              		                          		<div class="col s12 m4 l11">
	              		                          			<p class="">	
		                  		                          		<b>Steven Gerrard </b> <a href="#" class="ultra-small red-text">Remove</a> 
		                  		                          	</p>
	              		                          		</div>
              		                          		</div>
              		                          		<div class="row">
						                    			<div class="col s12 m4 l1">
	              		                          			<img src="images/user/gerrard.png" style="border-radius:50%;" width="32px" height="32px" alt="Profile" />
	              		                          		</div>
	              		                          		<div class="col s12 m4 l11">
	              		                          			<p class="">	
		                  		                          		<b>Steven Gerrard </b> <a href="#" class="ultra-small red-text">Remove</a> 
		                  		                          	</p>
                  		                          		</div>
              		                          		</div>
					                    		</div>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
									<div id="modalcreatelist" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Create a list..</b></h6>
					                    		<div class="divider"></div>
					                    		<p>Title</p>
					                    		<input type="text" placeholder="Title..">
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalcreatecard" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Create a card..</b></h6>
					                    		<div class="divider"></div>
					                    		<p>Title</p>
					                    		<input type="text" placeholder="Title..">
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalcalendar" class="modal" style="height:500%;">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
								              	<h6><b>Calendar Board</b></h6>    
								                <div class="col s12 m8 l12">
									                  <div id='calendar'></div>
									            </div>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalmore" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
								              	<h6><b>More Menu..</b></h6>    
								                <div class="col s12 m6 l6">
								                	<div class="col s12 m6 l12">
								                		<a class="btn-flat dropdown-button waves-effect black-text" href="#!" data-activates="dropdownboard">Change Background<i class="mdi-navigation-arrow-drop-down right"></i></a>
							                  				<ul id="dropdownboard" class="dropdown-content">
									                            <li>
									                            	<div class="col s12 m6 l9">
									                            		<div style="background-color:red;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
									                            	</div>
									                            	<div class="col s12 m6 l2">
									                            		<i style="margin:5px;" class="mdi-navigation-check black-text"></i>
									                            	</div>
                          										</li>
                          										<li>
									                            	<div class="col s12 m6 l9">
									                            		<div style="background-color:yellow;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
									                            	</div>
									                            	<div class="col s12 m6 l2">
									                            	</div>
                          										</li>
                          										<li>
									                            	<div class="col s12 m6 l9">
									                            		<div style="background-color:green;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
									                            	</div>
									                            	<div class="col s12 m6 l2">
									                            	</div>
                          										</li>
                          										<li>
									                            	<div class="col s12 m6 l9">
									                            		<div style="background-color:blue;width:100%;height:100%;margin:5px;top:0px;left:0px;border-radius:5%;">&nbsp</div>
									                            	</div>
									                            	<div class="col s12 m6 l2">
									                            	</div>
                          										</li>
								                         	</ul>
								                	</div>
								                	<div class="col s12 m6 l12">
								                		<p>
								                		<input type="checkbox" id="testfav" />
                      									<label for="testfav" class="black-text">Favorite</label>
								                		</p>
								                	</div>
								                	<div class="col s12 m6 l12">
								                		<p>
								                		<input type="checkbox" id="testsub" />
                      									<label for="testsub" class="black-text">Subscribe</label>
								                		</p>
								                	</div>
								                	<div class="divider"></div>
								                	<div class="col s12 m6 l12">
								                		<a class="btn-flat waves-effect black-text" href="#!">Leave Board</a>
								                	</div>

									            </div>
									            <div class="col s12 m6 l6">
									            	<div class="col s12 m6 l12">
								                		<a class="btn-flat waves-effect black-text modal-trigger" href="#modaleditboard">Edit Board</a>
								                	</div>
									            	<div class="col s12 m6 l12">
								                		<a class="btn-flat waves-effect black-text modal-trigger" href="#modalcopyboard">Copy Board</a>
								                	</div>
								                	<div class="col s12 m6 l12">
								                		<a class="btn-flat waves-effect black-text" href="#!">Print</a>
								                	</div>
								                	<div class="col s12 m6 l12">
								                		<a class="btn-flat dropdown-button waves-effect black-text" href="#!" data-activates="dropdownexport">Export<i class="mdi-navigation-arrow-drop-down right"></i></a>
								                		
								                		<ul id="dropdownexport" class="dropdown-content">
								                            <li>
								                            	<a href="#">PDF</a>
                      										</li>
                      										<li>
                      											<a href="#">Excel</a>
                      										</li>
							                         	</ul>
								                	</div>
								                	<div class="divider"></div>
								                	<div class="col s12 m6 l12">
								                		<a class="btn-flat waves-effect black-text modal-trigger" href="#modalarchive">Archive</a>
								                	</div>
								                	<div class="divider"></div>
								                	<div class="col s12 m6 l12">
								                		<a class="btn-flat waves-effect black-text" href="#!">Close Board</a>
								                	</div>

									            </div>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  </div>
					                </div>

									<!-- END OF MODAL MENU BOARD-->
									<!-- MODAL LIST-->
									<div id="modalcopylist" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Copy list..</b></h6>
					                    		<div class="divider"></div>
					                    		<p>Title</p>
					                    		<input type="text" placeholder="Title..">
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalmovelist" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Move list..</b></h6>
					                    		<p>Board</p>
					                    		<select>
							                      <option value="" disabled selected>Choose your option</option>
							                      <option value="1" selected>Bucket List</option>
							                      <option value="2">Life Goals</option>
							                      <option value="3">Praktikum (STTS 2017)</option>
							                    </select>
					                    		<div class="divider"></div>
					                    		<p>Position</p>
					                    		<select>
							                      <option value="" disabled selected>Choose your option</option>
							                      <option value="1" selected>1</option>
							                      <option value="2">2</option>
							                      <option value="3">3</option>
							                    </select>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalmovecardlist" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Move all card in this list..</b></h6>
					                    		<p>List</p>
					                    		<select>
							                      <option value="" disabled selected>Choose your option</option>
							                      <option value="1" selected>To Do (current)</option>
							                      <option value="2">In Progress</option>
							                      <option value="3">Done</option>
							                    </select>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
									<!-- END OF MODAL LIST-->
									<!-- MODAL MENU MORE-->
									<div id="modaleditboard" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Edit board..</b></h6>
					                    		<div class="divider"></div>
					                    		<p>Title</p>
					                    		<input type="text" value="Bucket List">
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalcopyboard" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Copy board..</b></h6>
					                    		<div class="divider"></div>
					                    		<p>Title</p>
					                    		<input type="text" value="Bucket List">
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
									<!-- END OF MODAL MENU MORE-->
									<!-- MODAL ACTION CARD-->
									<div id="modaleditcard" class="modal">
					                  <div class="modal-content">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Edit card..</b></h6>
					                    		<div class="divider"></div>
					                    		<p>Title</p>
					                    		<input type="text" value="Card Satu">
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalassignmembers" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Assign members</b></h6>
					                    		<div class="divider"></div>
					                    		<p>
						                    		<input type="checkbox" id="test3" />
							                     	<label for="test3" class="black-text">Michael Chandra</label>
						                     	</p>
						                     	<p>
							                     	<input type="checkbox" id="test3" />
							                     	<label for="test3" class="black-text">Steven Gerrard</label>
						                     	</p>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modallabelcard" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Label a card..</b></h6>
					                    		<div class="divider"></div>
					                    			<p>Choose your color..</p>
					                    			<input type="checkbox" style="margin-top:10px;" id="filterred" />
							                      	<label for="filterred"><div style="background-color:red;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
						                      		
						                      		<input type="checkbox" style="margin-top:5px;" id="filteryellow" />
							                      	<label for="filteryellow" ><div style="background-color:yellow;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
						                      		<input type="checkbox" style="margin-top:5px;" id="filtergreen" />
							                      	<label for="filtergreen"><div style="background-color:green;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
						                      		<input type="checkbox" style="margin-top:5px;"id="filterblue" />
							                      	<label for="filterblue"><div style="background-color:blue;width:32px;height:32px;border-radius:15%;margin-left:-12px;margin-top:-5px;margin-right:12px;"></div></label>
						
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
									<div id="modalchecklist" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Add a checklist..</b></h6>
					                    		<div class="divider"></div>
					                    		<p>Title</p>
					                    		<input type="text">
					                    		<p>Copy checklist from..</p>
							                    <select>
							                      <option value="" disabled selected>Choose your option</option>
							                      <option value="1">Card Satu (List To Do)</option>
							                      <option value="2">Card Satu (List In Progress)</option>
							                      <option value="3">Card Tiga (List Done)</option>
							                    </select>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalarchive" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Archived items..</b></h6>
					                    		<div class="divider"></div>
					                    		<div class="col s12 m6 l6">
					                    			<p><b>Cards</b></p>
					                    			<div class="divider"></div>
					                    			<p>Card Satu <a href="#" class="ultra-small green-text">Send to Board </a><a href="#" class="ultra-small red-text">Delete</a></p>
					                    			<p>Card Dua <a href="#" class="ultra-small green-text">Send to Board </a><a href="#" class="ultra-small red-text">Delete</a></p>
					                    		</div>
					                    		<div class="col s12 m6 l6">
					                    			<p><b>Lists</b></p>
					                    			<div class="divider"></div>
					                    			<p>List Satu <a href="#" class="ultra-small green-text">Send to Board </a><a href="#" class="ultra-small red-text">Delete</a></p>
					                    			<p>List Dua <a href="#" class="ultra-small green-text">Send to Board </a><a href="#" class="ultra-small red-text">Delete</a></p>
					                    		</div>
					                    	</div>
					                    </div>

					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalstartdate" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12" >
					                    	<div class="section">
					                    		<h6><b>Add a start date</b></h6>
					                    		<div class="divider"></div>
					                    		<div class="col s12 m6 l3">
					                    			<p>Date</p>
					                    			<input type="date" class="datepicker">
					                    			<p>Time</p>
								                    <select>
								                      <option value="" disabled selected>Choose your time</option>
								                      <option value="0">12:00AM</option>
								                      <option value="1">01:00AM</option>
								                      <option value="2">02:00AM</option>
								                      <option value="3">03:00AM</option>
								                      <option value="4">04:00AM</option>
								                      <option value="5">05:00AM</option>
								                      <option value="6">06:00AM</option>
								                      <option value="7">07:00AM</option>
								                      <option value="8">08:00AM</option>
								                      <option value="9">09:00AM</option>
								                      <option value="10">10:00AM</option>
								                      <option value="11">11:00AM</option>
								                      <option value="12" selected>12:00PM</option>
								                      <option value="13">01:00PM</option>
								                      <option value="14">02:00PM</option>
								                      <option value="15">03:00PM</option>
								                      <option value="16">04:00PM</option>
								                      <option value="17">05:00PM</option>
								                      <option value="18">06:00PM</option>
								                      <option value="19">07:00PM</option>
								                      <option value="20">08:00PM</option>
								                      <option value="21">09:00PM</option>
								                      <option value="22">10:00PM</option>
								                      <option value="23">11:00PM</option>
								                    </select>
					                    		</div>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalduedate" class="modal modal-fixed-footer white" style="height:80%">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12" >
					                    	<div class="section">
					                    		<h6><b>Add a due date</b></h6>
					                    		<div class="divider"></div>
					                    		<div class="col s12 m6 l3">
					                    			<p>Date</p>
					                    			<input type="date" class="datepicker">
					                    			<p>Time</p>
								                    <select>
								                      <option value="" disabled selected>Choose your time</option>
								                      <option value="0">12:00AM</option>
								                      <option value="1">01:00AM</option>
								                      <option value="2">02:00AM</option>
								                      <option value="3">03:00AM</option>
								                      <option value="4">04:00AM</option>
								                      <option value="5">05:00AM</option>
								                      <option value="6">06:00AM</option>
								                      <option value="7">07:00AM</option>
								                      <option value="8">08:00AM</option>
								                      <option value="9">09:00AM</option>
								                      <option value="10">10:00AM</option>
								                      <option value="11">11:00AM</option>
								                      <option value="12" selected>12:00PM</option>
								                      <option value="13">01:00PM</option>
								                      <option value="14">02:00PM</option>
								                      <option value="15">03:00PM</option>
								                      <option value="16">04:00PM</option>
								                      <option value="17">05:00PM</option>
								                      <option value="18">06:00PM</option>
								                      <option value="19">07:00PM</option>
								                      <option value="20">08:00PM</option>
								                      <option value="21">09:00PM</option>
								                      <option value="22">10:00PM</option>
								                      <option value="23">11:00PM</option>
								                    </select>
					                    		</div>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalattachment" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Add a attachment..</b></h6>
					                    		<div class="divider"></div>
					                    		<a class="btn-flat dropdown-button waves-effect blue-text" href="#!">Computer</a>
				                    			<a class="btn-flat dropdown-button waves-effect blue-text" href="#!">Google Drive</a>
			                    				<a class="btn-flat dropdown-button waves-effect blue-text" href="#!">Dropbox</a>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalmove" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Move card..</b></h6>
					                    		<div class="divider"></div>
					                    		<div class="col s12 m6 l12">
					                    			<p>Board</p>
					                    			<select>
								                      <option value="" disabled>My Boards</option>
								                      <option value="0" selected>Bucket List</option>
								                      <option value="0">Life Goals</option>
								                      <option value="" disabled>STTS 2017</option>
								                      <option value="0">Praktikum</option>
								                    </select>
					                    		</div>
					                    		<div class="col s12 m6 l6">
					                    			<p>List</p>
					                    			<select>
								                      <option value="0">To Do</option>
								                      <option value="0">Doing</option>
								                      <option value="0">Done</option>
								                    </select>
					                    		</div>
					                    		<div class="col s12 m6 l6">
					                    			<p>Position</p>
					                    			<select>
								                      <option value="0">1</option>
								                      <option value="0">2</option>
								                      <option value="0">3</option>
								                    </select>
					                    		</div>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <div id="modalcopy" class="modal modal-fixed-footer white">
					                  <div class="modal-content white">
					                    <div class="col s12 m6 l12">
					                    	<div class="row">
					                    		<h6><b>Copy card..</b></h6>
					                    		<div class="divider"></div>
					                    		<div class="col s12 m6 l12">
					                    			<input type="text" placeholder="Title" value="Card Satu">
					                    		</div>
					                    		<div class="col s12 m6 l12">
					                    			<p>Board</p>
					                    			<select>
								                      <option value="" disabled>My Boards</option>
								                      <option value="0" selected>Bucket List</option>
								                      <option value="0">Life Goals</option>
								                      <option value="" disabled>STTS 2017</option>
								                      <option value="0">Praktikum</option>
								                    </select>
					                    		</div>
					                    		<div class="col s12 m6 l6">
					                    			<p>List</p>
					                    			<select>
								                      <option value="0">To Do</option>
								                      <option value="0">Doing</option>
								                      <option value="0">Done</option>
								                    </select>
					                    		</div>
					                    		<div class="col s12 m6 l6">
					                    			<p>Position</p>
					                    			<select>
								                      <option value="0">1</option>
								                      <option value="0">2</option>
								                      <option value="0">3</option>
								                    </select>
					                    		</div>
					                    	</div>
					                    </div>
					                  </div>
					                  <div class="modal-footer teal lighten-4">
					                    <a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
					                  	<a href="#" class="waves-effect waves-red btn-flat modal-action modal-close">Save</a>
					                  </div>
					                </div>
					                <!-- END OF MODAL ACTION CARD-->
									<div class="card-content grey lighten-2 white-text">
				                        <p class=" grey-text text-darken-4 truncate" style="font-weight:bold;font-size:150%;">To Do<a href="#" class="activator black-text"><i class="mdi-navigation-more-vert right"></i></a></p>
										<a href="#modal3" class="modal-trigger">
											<!-- CARD -->
											<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
												<div class="left-align black-text" style="font-size=100%;">Card Satu</div>
											</div>
										</a>
										<!-- MODAL CARD-->
						                <div id="modal3" class="modal modal-fixed-footer grey lighten-3">
						                  <div class="modal-content grey lighten-3 black-text left-align">
						                  		<div class="row">
							                  		<div class="col s12 m6 l9">
							                  			<div class="row">
							                  				<div class="col s12 m6 l12">
								                  			<h5><b>Card Satu</b> <a href="#modaleditcard" class="ultra-small modal-trigger">Edit</a></h5>
								                  			</div>
							                  			</div>
							                  			<div class="row">
							                  				<div class="col s12 m6 l12">
									                  			<h6 class="grey-text lighten-3">in list To Do</h6>
								                  			</div>
									                  	</div>
									                  	<div class="divider"></div>
									                  	<div class="row">
							                  				<div class="col s12 m6 l12">
										                  		<h6><b>Description</b></h6>
									                  			<h6>Ini adalah deskripsi</h6>
									                  			<a href="#">Edit Description</a>
								                  			</div>
									                  	</div>
									                  	<div class="row">
									                  		<div class="col 12 m3 l4">
									                  			<h6><b>Members</b></h6>
									                  			<img src="images/user/gerrard.png" style="border-radius:50%;" width="32px" height="32px" alt="Profile" />
									                  			<img src="images/user/user2.png" style="border-radius:50%;" width="32px" height="32px" alt="Profile" />
									                  		</div>
									                  		<div class="col 12 m3 l2">
									                  			<h6><b>Label</b></h6>
									                  			<div style="width:32px;height:32px;border-radius:15%;background-color:green;"></div>
									                  		</div>
									                  		<div class="col s12 m3 l3">
									                  			<h6><b>Start Date</b></h6>
				                  			                    <p>
											                      <input type="checkbox" id="test1" />
											                      <label for="test1">Feb 26 at 12:00PM</label>
											                    </p>
									                  		</div>
									                  		<div class="col s12 m3 l3">
									                  			<h6><b>Due Date</b></h6>
				                  			                    <p>
											                      <input type="checkbox" id="test2" />
											                      <label for="test2">Feb 27 at 12:00PM</label>
											                    </p>
									                  		</div>
									                  	</div>
								                  		<div class="divider"></div>
									                  	<div class="row">
									                  		<div class="col s12 m6 l12">
									                  			<h6><b>Attachment</b></h6>
									                  			<div class="col s12 m6 l2">
																	<img src="images/user/blessRNG.jpg" style="width:90px;height:70px;" alt="Profile" />
									                  			</div>
									                  			<div class="col s12 m6 l7" style="margin-left:12px;">
									                  				<p>blessRNG.jpg</p>
									                  				<p class="grey-text lighten-3">Added 11 minutes ago - <a href="#">Delete</a></p>
									                  				<p class="grey-text lighten-3">Download</p>
									                  			</div>
									                  		</div>
									                  	</div>
									                  	<div class="divider"></div>
									                  	<div class="row">
									                  		<div class="col s12 m6 l10 ">
									                  			<h6><b>Checklist</b></h6>
									                  			<div class="progress">
															        <div class="determinate" style="width: 50%"></div>
															    </div>
															    <p>
											                      <input type="checkbox" id="test3" />
											                      <label for="test3">Satu</label>
											                    </p>
											                    <p>
											                      <input type="checkbox" id="test4" />
											                      <label for="test4">Dua</label>
											                    </p>
											                    <p>
											                    	<a href="#">Add an item</a>
										                    	</p>
									                  		</div>
									                  		<div class="col s12 m6 l1 ">
									                  			<a href="#">Delete</a>
									                  		</div>
									                  	</div>
								                  		<div class="divider" style="margin-top:5px;"></div>
								                  		<div class="row">
								                  			<div class="col s12 m6 l12">
									                  		<h6><b>Add Comment</b></h6>
		                  		                          	<textarea id="textarea1" class="materialize-textarea"></textarea> <a class="waves-effect waves-light light-blue lighten-1 btn">Save</a>
		                  		                          	</div>
								                  		</div>
	                  		                          	<div class="divider" style="margin-top:5px;"></div>
								                  		<div class="row">
								                  			<div class="col s12 m6 l12">
	                  		                          		<h6><b>Activities</b></h6>
	                  		                          		</div>
	                  		                         	</div>
	                  		                          	<div class="row">
	                  		                          		<div class="col s12 m4 l1">
	                  		                          			<img src="images/user/gerrard.png" style="border-radius:50%;" width="32px" height="32px" alt="Profile" />
	                  		                          		</div>
	                  		                          		<div class="col s12 m4 l11">
	                  		                          			<p>	
			                  		                          		<b>Steven Gerrard</b>
			                  		                          	</p>
		                  		                          		<input type="text" value="This is my first comment">
			                  		                          	<p class="ultra-small grey-text lighten-1">
			                  		                          		yesterday at 8:17 PM
			                  		                          	</p>
			                  		                          	<div class="col s12 m4 l1">
			                  		                          		<img src="images/user/gerrard.png" style="border-radius:50%;" width="32px" height="32px" alt="Profile" />
			                  		                          	</div>
			                  		                          	<div class="col s12 m4 l11">
			                  		                          		<p>	
				                  		                          		<b>Steven Gerrard</b>
					                  		                          	</p>
				                  		                          		<input type="text" value="This is my second comment inside my first comment">
					                  		                          	<p class="ultra-small grey-text lighten-1">
					                  		                          		yesterday at 8:17 PM
				                  		                          	</p>
			                  		                          	</div>

	                  		                          		</div>
	                  		                          	</div>
	                  		                          	<div class="divider"></div>
	                  		                          	<div class="row">
	                  		                          		<div class="col s12 m4 l1">
	                  		                          		<img src="images/user/gerrard.png" style="border-radius:50%;" width="32px" height="32px" alt="Profile" />
	                  		                          		</div>
	                  		                          		<div class="col s12 m4 l11">
	                  		                          			<p>	
			                  		                          		<b>Steven Gerrard</b> added this card to To Do
			                  		                          	</p>
			                  		                          	<p class="ultra-small grey-text lighten-1">
			                  		                          		yesterday at 8:17 PM
			                  		                          	</p>
	                  		                          		</div>
	                  		                          			
	                  		                          	</div>
							                  		</div>
							                  		<div class="col s12 m6 l3">
							                  			<h5 class="large"><b>Add</b></h5>
							                  			<div class="divider"></div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modalassignmembers" class="modal-trigger btn-flat waves-effect" style="font-size:90%;">Assign Members</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modallabelcard" class="modal-trigger btn-flat waves-effect">Label Card</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modalchecklist" class="modal-trigger btn-flat waves-effect">Checklist</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modalstartdate" class="modal-trigger btn-flat waves-effect">Start Date</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modalduedate" class="modal-trigger btn-flat waves-effect">Due Date</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modalattachment" class="modal-trigger btn-flat waves-effect">Attachment</a>
							                  			</div>
							                  			<h5 class="large"><b>Menu</b></h5>
							                  			<div class="divider"></div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modalmove" class="modal-trigger btn-flat waves-effect">Move</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#modalcopy" class="modal-trigger btn-flat waves-effect">Copy</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#" class="btn-flat waves-effect">Archive</a>
							                  			</div>
							                  			<div class="divider"></div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#" class="btn-flat waves-effect">Send to Board</a>
							                  			</div>
							                  			<div class="row" style="margin-top:5px;">
							                  				<a href="#" class="btn-flat waves-effect">Delete</a>
							                  			</div>
							                  		</div>
							                  	</div>
						                  </div>
						                  <div class="modal-footer teal lighten-4">
						                    <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Close</a>
						                  </div>
						                </div>
						                <!-- END OF MODAL ACTION CARD-->
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Tiga</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Empat</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Lima</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Enam</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Tujuh</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Delapan</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text"><a href="#modalcreatecard" class="modal-trigger grey-text">Add a Card..</a></div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p><a href="#modalcreatecard" class="modal-trigger black-text">Add a card..</a></p>
										<p><a href="#modalcopylist" class="modal-trigger black-text">Copy list..</a></p>
										<p><a href="#modalmovelist" class="modal-trigger black-text">Move list..</a></p>
										<p><a href="#modalmovecardlist" class="modal-trigger black-text">Move all card in this list..</a></p>
										<p><a href="#" class="black-text">Archive all card in this list..</a></p>
										<p><a href="#" class="black-text">Archive this list..</a></p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">In Progress<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>
									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">Done<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">Note<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class=" grey-text text-darken-4 truncate normal"><b>Contoh Note</b><span class=" activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
										<p class=" grey-text text-darken-4 truncate small"><b>Contoh Note</b><span class=" activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">To Do<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">To Do<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">To Do<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">To Do<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey lighten-2 white-text">
				                        <p class="card-title grey-text text-darken-4">To Do<span class="card-title activator"><i class="mdi-navigation-more-vert right"></i></span></p>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Satu</div>
										</div>
										<div class="card-action" style="background-color:white;color:black;border-radius:5px;margin-top:8px;">
											<div class="left-align black-text">Card Dua Panjang Katanya</div>
										</div>
	                                    <div class="card-compare  grey lighten-2" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align grey-text">Add a Card..</div>
                                   		</div>

									</div>
           		                    <div class="card-reveal">
                                    	<span class="card-title grey-text text-darken-4">List Menu <i class="mdi-navigation-close right"></i></span>
                                    	<div class="divider"></div>
				                        <p>Add a card..</p>
										<p>Copy list..</p>
										<p>Move list..</p>
										<p>Move all card in this list..</p>
										<p>Archive all card in this list..</p>
										<p>Archive this list..</p>
				                     </div>
								</div>
							</div>
							<div class="col s12 m6 l2">
								<div class="card">
									<div class="card-content grey white-text">
	                                    <div class="card-compare  grey" style="margin-top:8px;border-radius:5px;">
                                       		<div id="invoice-line" class="left-align white-text"><a href="#modalcreatelist" class="modal-trigger white-text">Add a List..</a></div>
                                   		</div>

									</div>
								</div>
							</div>
						</div>
					</div>
				
				</div>





				<!-- Floating Action Button -->
				<div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
					<a class="btn-floating btn-large">
					  <i class="mdi-action-stars"></i>
					</a>
					<ul>
					  <li><a href="css-helpers.html" class="btn-floating red"><i class="large mdi-communication-live-help"></i></a></li>
					  <li><a href="app-widget.html" class="btn-floating yellow darken-1"><i class="large mdi-device-now-widgets"></i></a></li>
					  <li><a href="app-calendar.html" class="btn-floating green"><i class="large mdi-editor-insert-invitation"></i></a></li>
					  <li><a href="app-email.html" class="btn-floating blue"><i class="large mdi-communication-email"></i></a></li>
					</ul>
				</div>
				<!-- Floating Action Button -->
			</div>
			<!--end container-->
		</section>
		<!-- END CONTENT -->
		      <!-- START RIGHT SIDEBAR NAV-->
  	<aside id="right-sidebar-nav">
        <ul id="chat-out" class="side-nav rightside-navigation">
            <li class="li-hover">
            <a href="#" data-activates="chat-out" class="chat-close-collapse right"><i class="mdi-navigation-close"></i></a>
            <div id="right-search" class="row">
                <form class="col s12">
                    <div class="input-field">
                        <i class="mdi-communication-chat prefix"></i>
                        <input id="icon_prefix" type="text" class="validate">
                        <label for="icon_prefix">Chat</label>
                    </div>
                </form>
            </div>
            </li>
            <li class="li-hover">
                <ul class="chat-collapsible" data-collapsible="expandable">
                <li>
                    <div class="collapsible-header red white-text active"><i class="mdi-action-stars"></i>Chat Board</div>
                    <div class="collapsible-body favorite-associates">
                        <div class="favorite-associate-list chat-out-list row">
                            <div class="col s4"><img src="images/user/user2.png" alt="" class="circle responsive-img online-user valign profile-image">
                            </div>
                            <div class="col s8">
                                <p>Michael</p>
                                <p class="place black-text">No?</p>
                                <p class="ultra-small grey-text lighten-3">just now</p>
                            </div>
                        </div>
                        <div class="favorite-associate-list chat-out-list row">
                            <div class="col s4"><img src="images/user/gerrard.png" alt="" class="circle responsive-img online-user valign profile-image">
                            </div>
                            <div class="col s8">
                                <p>Steven Gerrard</p>
                                <p class="place black-text">How are you?</p>
                                <p class="ultra-small grey-text lighten-3">5 minutes ago</p>
                            </div>
                        </div>
                    </div>
                    
                </li>
                <li>
            	<div class="collapsible-header teal white-text"><i class="mdi-social-whatshot"></i>Recent Activites</div>
                    <div class="collapsible-body recent-activity">
                        <div class="recent-activity-list chat-out-list row">
                            <div class="col s3 recent-activity-list-icon"><i class="mdi-action-add-shopping-cart"></i>
                            </div>
                            <div class="col s9 recent-activity-list-text">
                                <a href="#">just now</a>
                                <p>Jim Doe Purchased new equipments for zonal office.</p>
                            </div>
                        </div>
                        <div class="recent-activity-list chat-out-list row">
                            <div class="col s3 recent-activity-list-icon"><i class="mdi-device-airplanemode-on"></i>
                            </div>
                            <div class="col s9 recent-activity-list-text">
                                <a href="#">Yesterday</a>
                                <p>Your Next flight for USA will be on 15th August 2015.</p>
                            </div>
                        </div>
                    </div>
                </li>
                </ul>
            </li>
        </ul>
    </aside>

	</div>
	<!-- END WRAPPER -->
</div>
<!-- END MAIN -->