
  <div id="login-page" class="row">
    <div class="col s12 z-depth-4 card-panel">
      <form class="login-form formValidate" id="formValidate">
        <div class="row">
          <div class="input-field col s12 center">
            <h4>Register</h4>
            <p class="center">Join to our community now !</p>
          </div>
        </div>
        <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-social-person-outline prefix"></i>
            <input id="name" type="text" id="name">
            <label for="name" class="center-align">Your Name</label>

          </div>
          <div class="col s12" style="margin-left:15%;margin-top:-5%;display:none;" id="errorName">
            <label class="center-align red-text">Enter at least 3 characters.</label>
          </div>
        </div>
        <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-communication-email prefix"></i>
            <input id="email" type="email" id="email">
            <label for="email" class="center-align">Email</label>
          </div>
          <div class="col s12" style="margin-left:15%;margin-top:-5%;display:none;" id="errorEmail">
            <label class="center-align red-text">Enter a valid email.</label>
          </div>
        </div>
        <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-action-lock-outline prefix"></i>
            <input id="password" type="password" id="password">
            <label for="password">Password</label>
          </div>
          <div class="col s12" style="margin-left:15%;margin-top:-5%;display:none;" id="errorPass">
            <label class="center-align red-text">This field is required.</label>
          </div>
        </div>
        <div class="row margin">
          <div class="input-field col s12">
            <i class="mdi-action-lock-outline prefix"></i>
            <input id="confpassword" type="password" id="confpassword">
            <label for="confpassword">Password again</label>
          </div>
          <div class="col s12" style="margin-left:15%;margin-top:-5%;display:none;" id="errorcPass">
            <label class="center-align red-text">Please enter the same password again.</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <a class="btn waves-effect waves-light col s12" name="register" id="register" onclick="cekRegister()">Register Now</a>
          </div>
          <div class="input-field col s12">
            <div id="my-signin2" onclick="googleLogin()"></div>
          </div>
          <div class="input-field col s12">
            <p class="margin center medium-small sign-up">Already have an account? <a href="login">Login</a></p>
          </div>
        </div>
      </form>
    </div>
  </div>