<!DOCTYPE html>
<html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="msapplication-tap-highlight" content="no">
		<meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
		<meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
		<meta name="google-signin-client_id" content="1072527821213-ptf6v9avkb6hs1osqduk69bd9i5elmqd.apps.googleusercontent.com">
        <title>Taff</title>
        <!-- <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com"> -->

		<!-- Favicons-->
		<link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
		<!-- Favicons-->
		<link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
		<!-- For iPhone -->
		<meta name="msapplication-TileColor" content="#00bcd4">
		<meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
		<!-- For Windows Phone -->


		<!-- CORE CSS-->    
		<link href="css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection">
		<link href="css/style.min.css" type="text/css" rel="stylesheet" media="screen,projection">
		<!-- CSS style Horizontal Nav-->    
		<link href="css/layouts/style-horizontal.css" type="text/css" rel="stylesheet" media="screen,projection">
		<!-- Custome CSS-->    
		<link href="css/custom/custom.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <?php
            if(isset($sessUser))
            {
              echo '<link href="css/layouts/page-center.css" type="text/css" rel="stylesheet" media="screen,projection">';
            }
            $this->assets->outputCss();
        ?>
		<!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
        <link href="js/plugins/prism/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
		<link href="js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
		<link href="js/plugins/jvectormap/jquery-jvectormap.css" type="text/css" rel="stylesheet" media="screen,projection">
		<link href="js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="js/plugins/fullcalendar/css/fullcalendar.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="js/plugins/sweetalert/sweetalert.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="js/jquery-ui.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <style>
        .ui-draggable-helper {
             width:13%;
             border-radius:5px;
             padding: 6px;
             background: #fff;
             font-weight:150%;
            }
        </style>
	
    </head>
    <!-- jQuery Library -->
    <script type="text/javascript" src="js/plugins/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui.min.js"></script>
     <!--sweetalert -->
    <script type="text/javascript" src="js/plugins/sweetalert/sweetalert.min.js"></script> 
    <?php echo $this->getContent(); ?>
		<!-- ================================================
    Scripts
    ================================================ -->
    
    <!--materialize js-->
    <script type="text/javascript" src="js/materialize.min.js"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <!--prism-->
    <script type="text/javascript" src="js/plugins/prism/prism.js"></script>
    
    <!-- Calendar Script -->
    <script type="text/javascript" src="js/plugins/fullcalendar/lib/jquery-ui.custom.min.js"></script>
    <script type="text/javascript" src="js/plugins/fullcalendar/lib/moment.min.js"></script>
    <script type="text/javascript" src="js/plugins/fullcalendar/js/fullcalendar.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui.js"></script>
    <script type="text/javascript" src="js/jquery-ui.min.js"></script>
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="js/plugins.min.js"></script>
    <!--custom-script.js - Add your own theme custom JS-->
    <script type="text/javascript" src="js/custom-script.js"></script>
    <!-- chartist -->
    <script type="text/javascript" src="js/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script type="text/javascript" src="js/plugins/jquery-validation/additional-methods.min.js"></script>
    
    <!-- Toast Notification -->
    <!-- <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script> -->
    <!-- My JS-->
    <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
    <!--<script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>-->
</html>
