<?php
	$color = "";
	foreach($board as $r)
	{
		$color = $r->boardBackground;
	}
?>

<body id="layouts-horizontal" class="<?php echo $color ?>">
	<?php echo $this->getContent(); ?>
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="js/myjs/jsBoard.js"></script>
    <script type="text/javascript" src="js/myjs/jsDrive.js"></script>
</body>