<body id="layouts-horizontal" class="white">
	<?php echo $this->getContent(); ?>
    <script type="text/javascript" src="js/myjs/jsCalendar.js"></script>
    <script type="text/javascript" src="js/plugins/fullcalendar/lib/jquery-ui.custom.min.js"></script>
    <script type="text/javascript" src="js/plugins/fullcalendar/lib/moment.min.js"></script>
    <script type="text/javascript" src="js/plugins/fullcalendar/js/fullcalendar.min.js"></script>
</body>