<body id="layouts-horizontal" class="white">
    <?php 
        echo $this->getContent(); 
        $src = 'js/myjs/jsMgroup.js';
        echo $this->tag->javascriptInclude(array('src'=>$src.'?'.filemtime($src)));
    ?>
    <!--<script type="text/javascript" src="js/myjs/jsMgroup.js"></script>-->
    <script type="text/javascript" src="js/plugins/data-tables/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="js/plugins/data-tables/data-tables-script.js"></script>
</body>