<body id="layouts-horizontal" class="white">
    <?php echo $this->getContent(); ?>
    <?php
        use Phalcon\Mvc\Url;

        $url = new Url();
        $url->setBaseUri('/trello/');
        //echo $url->getBaseUri();
    ?>
    <script type="text/javascript" src="js/myjs/jsMgroup.js"></script>
    <script type="text/javascript" src="js/plugins/data-tables/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="js/plugins/data-tables/data-tables-script.js"></script>
</body>